### ISSUE TITLE
Issues running on Ubuntu 18.04

### ISSUE THREAD

**Issue by StanleyGoldman** [github-for-unity/Unity#1015]
Reported by @stanishev @firebaugh @kmcdowelljr in #950 
They are experiencing issues with using GitHub for Unity on Ubuntu.

These errors appear in their logs rather consistently, leading me to agree that it is a platform issue rather than a user issue.

1. Error during initialization of `RepositoryWatcher` & `SFW`
   ```
   190117-13:36:07 ERROR [ 4] <RepositoryWatcher>                 
   libsfw
     at (wrapper managed-to-native) sfw.net.UnixInterface/NativeCalls:NativeInterface_Create (string)
     at sfw.net.UnixInterface.Create (System.String path) [0x00000] in <filename unknown>:0 
     at sfw.net.NativeMethods.Create (System.String path) [0x00000] in <filename unknown>:0 
     at sfw.net.NativeInterface..ctor (System.String path) [0x00000] in <filename unknown>:0 
     at GitHub.Unity.RepositoryWatcher.Initialize () [0x00020] in G:\Git\Hub\github-for-unity\src\GitHub.Api\Events\RepositoryWatcher.cs:72 
     at GitHub.Unity.LogFacade.Error(System.Exception ex, System.String message) in G:\Git\Hub\github-for-unity\src\GitHub.Logging\LogFacade.cs:line 145
     at GitHub.Unity.LogFacade.Error(System.Exception ex) in G:\Git\Hub\github-for-unity\src\GitHub.Logging\LogFacade.cs:line 150
     at GitHub.Unity.RepositoryWatcher.Initialize() in G:\Git\Hub\github-for-unity\src\GitHub.Api\Events\RepositoryWatcher.cs:line 76
     at GitHub.Unity.RepositoryManager.Initialize() in G:\Git\Hub\github-for-unity\src\GitHub.Api\Git\RepositoryManager.cs:line 169
     at GitHub.Unity.ApplicationManagerBase.RestartRepository() in G:\Git\Hub\github-for-unity\src\GitHub.Api\Application\ApplicationManagerBase.cs:line 124
   ```

2. Saving System Settings
   ```
   190117-13:36:17 ERROR [ 1] <SystemSettings>                    SaveToCache Error
   Parent is called on an empty path
   at GitHub.Unity.NPath.get_Parent () [0x0000f] in G:\Git\Hub\github-for-unity\src\GitHub.Api\IO\NiceIO.cs:160
   at (wrapper dynamic-method) System.Runtime.CompilerServices.ExecutionScope.lambda_method (System.Runtime.CompilerServices.ExecutionScope,object) <IL 0x0000b, 0x000b0>
   at GitHub.Reflection.ReflectionUtils/<>c__DisplayClass33_0.<GetGetMethodByExpression>b__0 (object) [0x00001] in G:\Git\Hub\github-for-unity\src\GitHub.Api\Helpers\SimpleJson.cs:1910
   at GitHub.PocoJsonSerializerStrategy.TrySerializeUnknownTypes (object,object&) [0x0006a] in G:\Git\Hub\github-for-unity\src\GitHub.Api\Helpers\SimpleJson.cs:1510
   at GitHub.PocoJsonSerializerStrategy.TrySerializeNonPrimitiveObject (object,object&) [0x00001] in G:\Git\Hub\github-for-unity\src\GitHub.Api\Helpers\SimpleJson.cs:1324
   at GitHub.SimpleJson.SerializeValue (GitHub.IJsonSerializerStrategy,object,System.Text.StringBuilder) [0x000f8] in G:\Git\Hub\github-for-unity\src\GitHub.Api\Helpers\SimpleJson.cs:1041
   at GitHub.SimpleJson.SerializeObject (GitHub.IJsonSerializerStrategy,System.Collections.IEnumerable,System.Collections.IEnumerable,System.Text.StringBuilder) [0x00089] in G:\Git\Hub\github-for-unity\src\GitHub.Api\Helpers\SimpleJson.cs:1069
   at GitHub.SimpleJson.SerializeValue (GitHub.IJsonSerializerStrategy,object,System.Text.StringBuilder) [0x00032] in G:\Git\Hub\github-for-unity\src\GitHub.Api\Helpers\SimpleJson.cs:1018
   at GitHub.SimpleJson.SerializeValue (GitHub.IJsonSerializerStrategy,object,System.Text.StringBuilder) [0x00109] in G:\Git\Hub\github-for-unity\src\GitHub.Api\Helpers\SimpleJson.cs:1043
   at GitHub.SimpleJson.SerializeObject (GitHub.IJsonSerializerStrategy,System.Collections.IEnumerable,System.Collections.IEnumerable,System.Text.StringBuilder) [0x00089] in G:\Git\Hub\github-for-unity\src\GitHub.Api\Helpers\SimpleJson.cs:1069
   at GitHub.SimpleJson.SerializeValue (GitHub.IJsonSerializerStrategy,object,System.Text.StringBuilder) [0x00032] in G:\Git\Hub\github-for-unity\src\GitHub.Api\Helpers\SimpleJson.cs:1018
   at GitHub.SimpleJson.SerializeValue (GitHub.IJsonSerializerStrategy,object,System.Text.StringBuilder) [0x00109] in G:\Git\Hub\github-for-unity\src\GitHub.Api\Helpers\SimpleJson.cs:1043
   at GitHub.SimpleJson.SerializeObject (GitHub.IJsonSerializerStrategy,System.Collections.IEnumerable,System.Collections.IEnumerable,System.Text.StringBuilder) [0x00089] in G:\Git\Hub\github-for-unity\src\GitHub.Api\Helpers\SimpleJson.cs:1069
   at GitHub.SimpleJson.SerializeValue (GitHub.IJsonSerializerStrategy,object,System.Text.StringBuilder) [0x00032] in G:\Git\Hub\github-for-unity\src\GitHub.Api\Helpers\SimpleJson.cs:1018
   at GitHub.SimpleJson.SerializeValue (GitHub.IJsonSerializerStrategy,object,System.Text.StringBuilder) [0x00109] in G:\Git\Hub\github-for-unity\src\GitHub.Api\Helpers\SimpleJson.cs:1043
   at GitHub.SimpleJson.SerializeObject (GitHub.IJsonSerializerStrategy,System.Collections.IEnumerable,System.Collections.IEnumerable,System.Text.StringBuilder) [0x00089] in G:\Git\Hub\github-for-unity\src\GitHub.Api\Helpers\SimpleJson.cs:1069
   at GitHub.SimpleJson.SerializeValue (GitHub.IJsonSerializerStrategy,object,System.Text.StringBuilder) [0x00032] in G:\Git\Hub\github-for-unity\src\GitHub.Api\Helpers\SimpleJson.cs:1018
   at GitHub.SimpleJson.SerializeObject (GitHub.IJsonSerializerStrategy,System.Collections.IEnumerable,System.Collections.IEnumerable,System.Text.StringBuilder) [0x00089] in G:\Git\Hub\github-for-unity\src\GitHub.Api\Helpers\SimpleJson.cs:1069
   at GitHub.SimpleJson.SerializeValue (GitHub.IJsonSerializerStrategy,object,System.Text.StringBuilder) [0x00032] in G:\Git\Hub\github-for-unity\src\GitHub.Api\Helpers\SimpleJson.cs:1018
   at GitHub.SimpleJson.SerializeValue (GitHub.IJsonSerializerStrategy,object,System.Text.StringBuilder) [0x00109] in G:\Git\Hub\github-for-unity\src\GitHub.Api\Helpers\SimpleJson.cs:1043
   at GitHub.SimpleJson.SerializeObject (object,GitHub.IJsonSerializerStrategy) [0x0000c] in G:\Git\Hub\github-for-unity\src\GitHub.Api\Helpers\SimpleJson.cs:607
   at GitHub.SimpleJson.SerializeObject (object) [0x00001] in G:\Git\Hub\github-for-unity\src\GitHub.Api\Helpers\SimpleJson.cs:613
   at GitHub.Unity.JsonBackedSettings.SaveToCache (string) [0x00025] in G:\Git\Hub\github-for-unity\src\GitHub.Api\Platform\Settings.cs:151

      at GitHub.Unity.LogFacade.Error(System.Exception ex, System.String message) in G:\Git\Hub\github-for-unity\src\GitHub.Logging\LogFacade.cs:line 145
      at GitHub.Unity.JsonBackedSettings.SaveToCache(System.String path) in G:\Git\Hub\github-for-unity\src\GitHub.Api\Platform\Settings.cs:line 156
      at GitHub.Unity.JsonBackedSettings.Set(System.String key, GitHub.Unity.NPath value) in G:\Git\Hub\github-for-unity\src\GitHub.Api\Platform\Settings.cs:line 87
      at GitHub.Unity.SettingsView.<OnInstallPathGUI>b__56_1(Boolean success, System.Exception ex, GitHub.Unity.NPath path) in G:\Git\Hub\github-for-unity\src\UnityExtension\Assets\Editor\GitHub.Unity\UI\SettingsView.cs:line 533
      at GitHub.Unity.ActionTask`1[[GitHub.Unity.NPath, GitHub.Api, Version=0.20.0.0, Culture=neutral, PublicKeyToken=null]].Run(Boolean success, GitHub.Unity.NPath previousResult) in G:\Git\Hub\github-for-unity\src\GitHub.Api\NewTaskSystem\ActionTask.cs:line 113
      at GitHub.Unity.ActionTask`1[[GitHub.Unity.NPath, GitHub.Api, Version=0.20.0.0, Culture=neutral, PublicKeyToken=null]].<.ctor>b__7_0() in G:\Git\Hub\github-for-unity\src\GitHub.Api\NewTaskSystem\ActionTask.cs:line 90
      at System.Threading.Tasks.Task.InnerInvoke()
      at System.Threading.Tasks.Task.Execute()
      at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object obj)
      at System.Security.SecurityContext.Run(System.Security.SecurityContext securityContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Security/SecurityContext.cs:line 150
      at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
      at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef currentTaskSlot)
      at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
      at System.Threading.Tasks.SynchronizationContextTaskScheduler.PostCallback(System.Object obj)
      at GitHub.Unity.MainThreadSynchronizationContext+<>c__DisplayClass2_0.<Post>b__0() in G:\Git\Hub\github-for-unity\src\UnityExtension\Assets\Editor\GitHub.Unity\Threading\SingleThreadSynchronizationContext.cs:line 23
      at UnityEditor.EditorApplication.Internal_CallDelayFunctions() in /home/builduser/buildslave/unity/build/Editor/Mono/EditorApplication.cs:line 200
   ```

3. Logging in
   ```
   190117-13:36:32  INFO [ 1] <LoginManager>                      Login Username:firebaugh
   190117-13:36:34  WARN [ 1] <LoginManager>                      Login Exception
   An error occurred while sending the request
     at System.Net.Http.HttpClientHandler+<SendAsync>c__async0.MoveNext () [0x00000] in <filename unknown>:0 
      at GitHub.Unity.LogFacade.Warning(System.Exception ex, System.String message) in G:\Git\Hub\github-for-unity\src\GitHub.Logging\LogFacade.cs:line 120
      at GitHub.Unity.LoginManager+<Login>d__8.MoveNext() in G:\Git\Hub\github-for-unity\src\GitHub.Api\Authentication\LoginManager.cs:line 124
      at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object stateMachine)
      at System.Security.SecurityContext.Run(System.Security.SecurityContext securityContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Security/SecurityContext.cs:line 150
      at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
      at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
      at System.Runtime.CompilerServices.TaskAwaiter+<>c.<OnCompletedInternal>b__17_1(System.Object state)
      at GitHub.Unity.MainThreadSynchronizationContext+<>c__DisplayClass2_0.<Post>b__0() in G:\Git\Hub\github-for-unity\src\UnityExtension\Assets\Editor\GitHub.Unity\Threading\SingleThreadSynchronizationContext.cs:line 23
      at UnityEditor.EditorApplication.Internal_CallDelayFunctions() in /home/builduser/buildslave/unity/build/Editor/Mono/EditorApplication.cs:line 200
   ```
4. `git lfs locks`
   ```
   190117-14:15:11 TRACE [ 6] <TaskManager>                       Exception on exclusive thread: 3 git lfs locks
   ApplicationName='/home/cait/.local/share/GitHubUnity/PortableGit_f02737a78695063deace08e96d5042710d3e32db/bin/git', CommandLine='lfs locks', CurrentDirectory='/home/cait/embodied/bo-android'
     at System.Diagnostics.Process.Start_noshell (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process) [0x00000] in <filename unknown>:0 
     at System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process) [0x00000] in <filename unknown>:0 
     at System.Diagnostics.Process.Start () [0x00000] in <filename unknown>:0 
     at (wrapper remoting-invoke-with-check) System.Diagnostics.Process:Start ()
     at GitHub.Unity.ProcessWrapper.Run () [0x0006f] in G:\Git\Hub\github-for-unity\src\GitHub.Api\NewTaskSystem\ProcessTask.cs:178 
      at GitHub.Unity.LogFacade.Trace(System.Exception ex, System.String message) in G:\Git\Hub\github-for-unity\src\GitHub.Logging\LogFacade.cs:line 91
      at GitHub.Unity.TaskManager+<>c__DisplayClass26_0`1[[GitHub.Unity.TaskBase, GitHub.Api, Version=0.20.0.0, Culture=neutral, PublicKeyToken=null]].<ScheduleExclusive>b__0(System.Threading.Tasks.Task tt) in G:\Git\Hub\github-for-unity\src\GitHub.Api\NewTaskSystem\TaskManager.cs:line 123
      at System.Threading.Tasks.Task+<>c__DisplayClass6.<ContinueWith>b__5(System.Object obj)
      at System.Threading.Tasks.Task.InnerInvoke()
      at System.Threading.Tasks.Task.Execute()
      at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object obj)
      at System.Security.SecurityContext.Run(System.Security.SecurityContext securityContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Security/SecurityContext.cs:line 150
      at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
      at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef currentTaskSlot)
      at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
      at System.Threading.Tasks.TaskScheduler.TryExecuteTask(System.Threading.Tasks.Task task)
      at GitHub.Unity.ConcurrentExclusiveInterleave+ConcurrentExclusiveTaskScheduler.ExecuteTask(System.Threading.Tasks.Task task) in G:\Git\Hub\github-for-unity\src\GitHub.Api\NewTaskSystem\ConcurrentExclusiveInterleave.cs:line 398
      at GitHub.Unity.ConcurrentExclusiveInterleave.ExecuteConcurrentTask(System.Threading.Tasks.Task task) in G:\Git\Hub\github-for-unity\src\GitHub.Api\NewTaskSystem\ConcurrentExclusiveInterleave.cs:line 214
      at System.Threading.Tasks.Parallel+<>c__DisplayClass32`2[[System.Threading.Tasks.Task, System.Threading, Version=1.0.3333.0, Culture=neutral, PublicKeyToken=402899b480e6f383],[System.Object, mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<PartitionerForEachWorker>b__30()
      at System.Threading.Tasks.Task.InnerInvoke()
      at System.Threading.Tasks.Task.InnerInvokeWithArg(System.Threading.Tasks.Task childTask)
      at System.Threading.Tasks.Task+<>c__DisplayClass3.<ExecuteSelfReplicating>b__2(System.Object )
      at System.Threading.Tasks.Task.ExecuteSelfReplicating(System.Threading.Tasks.Task root)
      at System.Threading.Tasks.Task.Execute()
      at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object obj)
      at System.Security.SecurityContext.Run(System.Security.SecurityContext securityContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Security/SecurityContext.cs:line 150
      at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
      at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef currentTaskSlot)
      at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
      at System.Reflection.MonoMethod.InternalInvoke(System.Object , System.Object[] , System.Exception ByRef )
      at System.Reflection.MonoMethod.Invoke(System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:line 222
      at System.Reflection.MethodBase.Invoke(System.Object obj, System.Object[] parameters) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:line 115
      at GitHub.Unity.TaskSchedulerExcludingThread.ExecuteEntry(System.Threading.Tasks.Task task, Boolean flag) in G:\Git\Hub\github-for-unity\src\GitHub.Api\NewTaskSystem\ConcurrentExclusiveInterleave.cs:line 33
      at GitHub.Unity.TaskSchedulerExcludingThread.TaskExecuteWaitCallback(System.Object obj) in G:\Git\Hub\github-for-unity\src\GitHub.Api\NewTaskSystem\ConcurrentExclusiveInterleave.cs:line 49
   ```

**Comment by mineus64** [comment]
Is there some sort of solution or workaround to this bug? It completely prevents usage of GitHub for Unity on all Linux OSes.

**Comment by datavikingr** [comment]
I'm having the same issue here. I can't login from Linux at all. 
Pop Os! 19.04 (Ubuntu fork) 
Latest Unity build for Linux 
Latest version of the extension.

**Comment by treierxyz** [comment]
Any news? Still doesn't work on Ubuntu 19.04.
