### ISSUE TITLE
FindExecTask fails; SettingsView never displays

### ISSUE THREAD

**Issue by rdurnin** [github-for-unity/Unity#297]
### Prerequisites

github-unity.log

```
170911-11:01:54  INFO [ 1] <Global>                            Initializing GitHub for Unity version 0.19.0
170911-11:01:54 TRACE [ 1] <IApplicationManager>               Run - CurrentDirectory /Users/rdurnin/Dev/leia/TestingGithubUnity
170911-11:01:54 TRACE [ 1] <GitInstaller>                      SetupIfNeeded
170911-11:01:54 TRACE [ 1] <GitInstaller>                      SetupGitIfNeeded
170911-11:01:54 TRACE [ 1] <GitInstaller>                      /Users/rdurnin/.local/share/GitHubUnity/PortableGit_f02737a78695063deace08e96d5042710d3e32db/bin/git not installed yet
170911-11:01:54  WARN [ 1] <GitInstaller>                      Archive "Assets/Plugins/GitHub/Editor/PlatformResources/mac/git.zip" missing
170911-11:01:54  WARN [ 1] <GitInstaller>                      Archive "Assets/Plugins/GitHub/Editor/Assets/Plugins/GitHub/Editor/PlatformResources/mac/git.zip" missing, returning
170911-11:01:54 TRACE [ 1] <GitInstaller>                      SetupGitLfsIfNeeded
170911-11:01:54 TRACE [ 1] <GitInstaller>                      GitLFS MD5: 54F586DF05A4B80FEAE4FABED10D8E95
170911-11:01:54 TRACE [ 1] <GitInstaller>                      GitLFS Present
170911-11:01:54 TRACE [ 1] <GitInstaller>                      Already extracted /Users/rdurnin/.local/share/GitHubUnity/PortableGit_f02737a78695063deace08e96d5042710d3e32db/libexec/git-core/git-lfs, returning
170911-11:01:54 TRACE [ 1] <IApplicationManager>               Finding git install path
170911-11:01:55 TRACE [ 3] <TaskManager>                       Exception on concurrent thread: 1 which
Object reference not set to an instance of an object
  at GitHub.Unity.ProcessWrapper.Run () [0x00000] in C:\Users\Spade\Projects\GitHub\Unity_master\src\GitHub.Api\NewTaskSystem\ProcessTask.cs:81 
  at GitHub.Unity.ProcessTask`1[T].RunWithReturn (Boolean success) [0x0005c] in C:\Users\Spade\Projects\GitHub\Unity_master\src\GitHub.Api\NewTaskSystem\ProcessTask.cs:309 
  at GitHub.Unity.TaskBase`1[TResult].<TaskBase>m__0 () [0x00000] in C:\Users\Spade\Projects\GitHub\Unity_master\src\GitHub.Api\NewTaskSystem\TaskBase.cs:406 
  at System.Threading.Tasks.Task`1[GitHub.Unity.NPath].InvokeFuture (System.Object futureAsObj) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <filename unknown>:0 
   at GitHub.Unity.LogFacade.Trace(System.Exception ex, System.String message) in C:\Users\Spade\Projects\GitHub\Unity_master\src\GitHub.Logging\LogFacade.cs:line 91
   at GitHub.Unity.TaskManager+<ScheduleConcurrent>c__AnonStorey2`1[[GitHub.Unity.TaskBase, GitHub.Api, Version=0.19.0.0, Culture=neutral, PublicKeyToken=null]].<>m__0(System.Threading.Tasks.Task tt) in C:\Users\Spade\Projects\GitHub\Unity_master\src\GitHub.Api\NewTaskSystem\TaskManager.cs:line 145
   at System.Threading.Tasks.Task+<>c__DisplayClass6.<ContinueWith>b__5(System.Object obj)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object obj)
   at System.Security.SecurityContext.Run(System.Security.SecurityContext securityContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Security/SecurityContext.cs:line 150
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.TaskScheduler.TryExecuteTask(System.Threading.Tasks.Task task)
   at GitHub.Unity.ConcurrentExclusiveInterleave+ConcurrentExclusiveTaskScheduler.ExecuteTask(System.Threading.Tasks.Task task) in C:\Users\Spade\Projects\GitHub\Unity_master\src\GitHub.Api\NewTaskSystem\ConcurrentExclusiveInterleave.cs:line 398
   at GitHub.Unity.ConcurrentExclusiveInterleave.ExecuteConcurrentTask(System.Threading.Tasks.Task task) in C:\Users\Spade\Projects\GitHub\Unity_master\src\GitHub.Api\NewTaskSystem\ConcurrentExclusiveInterleave.cs:line 214
   at System.Threading.Tasks.Parallel+<>c__DisplayClass32`2[[System.Threading.Tasks.Task, System.Threading, Version=1.0.3333.0, Culture=neutral, PublicKeyToken=402899b480e6f383],[System.Object, mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<PartitionerForEachWorker>b__30()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(System.Threading.Tasks.Task childTask)
   at System.Threading.Tasks.Task+<>c__DisplayClass3.<ExecuteSelfReplicating>b__2(System.Object )
   at System.Threading.Tasks.Task.ExecuteSelfReplicating(System.Threading.Tasks.Task root)
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object obj)
   at System.Security.SecurityContext.Run(System.Security.SecurityContext securityContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Security/SecurityContext.cs:line 150
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Reflection.MonoMethod.InternalInvoke(System.Object , System.Object[] , System.Exception ByRef )
   at System.Reflection.MonoMethod.Invoke(System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:line 222
   at System.Reflection.MethodBase.Invoke(System.Object obj, System.Object[] parameters) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:line 115
   at GitHub.Unity.TaskSchedulerExcludingThread.ExecuteEntry(System.Threading.Tasks.Task task, Boolean flag) in C:\Users\Spade\Projects\GitHub\Unity_master\src\GitHub.Api\NewTaskSystem\ConcurrentExclusiveInterleave.cs:line 33
   at GitHub.Unity.TaskSchedulerExcludingThread.TaskExecuteWaitCallback(System.Object obj) in C:\Users\Spade\Projects\GitHub\Unity_master\src\GitHub.Api\NewTaskSystem\ConcurrentExclusiveInterleave.cs:line 49
170911-11:01:55 TRACE [ 1] <IApplicationManager>               Restarted 
170911-11:04:54 TRACE [ 4] <UsageTracker>                      SendUsage
170911-11:04:54 TRACE [ 4] <UsageTracker>                      LoadUsage: "/Users/rdurnin/Library/Application Support/GitHubUnity/usage.json"
170911-11:04:54 TRACE [ 4] <UsageTracker>                      Sending Usage
170911-11:04:54 TRACE [ 4] <MetricsService>                    Post Usage
170911-11:04:54 TRACE [ 4] <MetricsService>                    Serializing 1 items
170911-11:04:54 TRACE [ 4] <MetricsService>                    Posting Content: [{"guid":"09053792-2193-4c56-b3aa-7cb6b4b97ef9","date":"2017-09-10T00:00:00Z","appVersion":"0.19.0.0","unityVersion":"2017.1.1f1","lang":"","numberOfStartups":1}]
170911-11:04:55 TRACE [ 4] <UsageTracker>                      SaveUsage: "/Users/rdurnin/Library/Application Support/GitHubUnity/usage.json"
```

### Description

Cannot authenticate on OSX.

### Steps to Reproduce

1. Create a new Unity project
2. Import custom github package.
3. Attempt to authenticate using the provided window.

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by StanleyGoldman** [comment]
Formatted the message some

**Comment by StanleyGoldman** [comment]
Okay, got the root cause of this issue..
