### ISSUE TITLE
Cannot commit any changes,

### ISSUE THREAD

**Issue by joehot200** [github-for-unity/Unity#601]
### Description

Using Unity 2017.3, I have just installed GitHub for Unity.

I have signed in, and I have linked GitHub to my repository.
The problem is, that LOCALLY, I cannot commit any changes.
![image](https://user-images.githubusercontent.com/6872507/36917811-bd65176e-1e4f-11e8-94c0-e58a4266bb26.png)

After clicking "Commit to [master]", nothing happens. I check the History tab, and nothing changes.
The files or amount of files do not seem to matter, the outcome is always the same - nothing happens.

![image](https://user-images.githubusercontent.com/6872507/36917846-d3dd58e4-1e4f-11e8-8cf9-7f6ee58259d4.png)

Furthermore, Unity also seems to be using up almost all of the RAM on my laptop since I installed Github for Unity. I'm not sure if that is relevant to the problem.

### Additional Information

Here is my log file:
180302-15:51:06.965  INFO [ 1] <Global>                            Initializing GitHub for Unity version 0.26.2
180302-16:49:41.781  INFO [ 1] <LoginManager>                      Login Username:joehot200 C:\Users\joeho\AppData\Local\GitHubUnity\tools\octorun.exe
180302-16:52:20.493  INFO [ 1] <LoginManager>                      Login Username:joehot200 C:\Users\joeho\AppData\Local\GitHubUnity\tools\octorun.exe
180302-17:03:51.213  WARN [ 1] <RepositoryWatcher>                 Watcher already stopped
180302-17:03:51.225  WARN [ 1] <RepositoryWatcher>                 Watcher already stopped
180302-18:10:21.470  WARN [ 2] <UsageTracker>                      No service, not sending usage
180302-18:10:21.665  WARN [ 3] <UsageTracker>                      No service, not sending usage

**Comment by shana** [comment]
Could you enable the Trace Logging check in the Settings tab of the GitHub window and send the log again after you've tried to commit? It'll generate more output that hopefully will tell us what the problem is.

**Comment by joehot200** [comment]
Thank you for your quick reply! Looks like there's an error. Here is the log:
```
180302-19:23:10.001  INFO [ 1] <Global>                            Initializing GitHub for Unity version 0.26.2
180302-19:33:24.194  INFO [ 1] <Global>                            Trace Logging Enabled
180302-19:33:24.201 TRACE [ 1] <UserSettings>                      Set: EnableTraceLogging
180302-19:33:24.207 TRACE [ 1] <UserSettings>                      SaveToCache: C:\Users\joeho\AppData\Local\GitHubUnity\settings.json
180302-19:33:26.394 TRACE [ 1] <SettingsView>                      OnDisable
180302-19:33:26.399 TRACE [ 1] <GitPathView>                       OnDisable
180302-19:33:26.406 TRACE [ 1] <UserSettingsView>                  OnDisable
180302-19:33:26.411 TRACE [ 1] <ChangesView>                       OnEnable
180302-19:33:26.415 TRACE [ 1] <Repository>                        Check RepositoryInfoCache CacheUpdateEvent Current:3/2/2018 4:37:09 PM +00:00 Check:3/2/2018 4:37:09 PM +00:00 Result:False
180302-19:33:26.419 TRACE [ 1] <Repository>                        Check GitStatusEntriesCache CacheUpdateEvent Current:3/2/2018 4:01:06 PM +00:00 Check:3/2/2018 4:01:06 PM +00:00 Result:False
180302-19:33:26.422 TRACE [ 1] <Repository>                        Check GitLocksCache CacheUpdateEvent Current:1/1/0001 12:00:00 AM +00:00 Check:1/1/0001 12:00:00 AM +00:00 Result:False
180302-19:33:34.984 TRACE [ 1] <GitClient>                         Add Files
180302-19:33:34.989 TRACE [ 1] <GitClient>                         Commit
180302-19:33:34.994 TRACE [19] <RepositoryManager>                 Starting Operation - Setting Busy Flag
180302-19:33:34.999 TRACE [19] <RepositoryManager>                 IsBusyChanged Value:True
180302-19:33:35.005 TRACE [19] <RepositoryManager>                 Starting Operation - Disable Watcher
180302-19:33:35.009 TRACE [19] <RepositoryWatcher>                 Stopping watcher
180302-19:33:35.181 TRACE [14] <RepositoryManager>                 Ended Operation - Enable Watcher
180302-19:33:35.187 TRACE [14] <RepositoryWatcher>                 Watching Path: "F:\Unity\TD2\TankDestruction"
180302-19:33:35.191 TRACE [14] <RepositoryManager>                 Ended Operation - Clearing Busy Flag
180302-19:33:35.191 TRACE [20] <RepositoryWatcher>                 Starting watcher
180302-19:33:35.194 TRACE [14] <RepositoryManager>                 IsBusyChanged Value:False
180302-19:33:35.206 TRACE [21] <TaskManager>                       Exception on exclusive thread: 2 git add
fatal: Unable to create 'F:/Unity/TD2/TankDestruction/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
  at GitHub.Unity.ProcessTask`1+<RunWithReturn>c__AnonStorey0[System.String].<>m__0 () [0x0010a] in D:\code\github\Unity\src\GitHub.Api\NewTaskSystem\ProcessTask.cs:301 
  at GitHub.Unity.ProcessWrapper.Run () [0x00332] in D:\code\github\Unity\src\GitHub.Api\NewTaskSystem\ProcessTask.cs:170 
  at GitHub.Unity.ProcessTask`1[T].RunWithReturn (Boolean success) [0x0005c] in D:\code\github\Unity\src\GitHub.Api\NewTaskSystem\ProcessTask.cs:311 
  at GitHub.Unity.TaskBase`1[TResult].<TaskBase>m__0 () [0x00000] in D:\code\github\Unity\src\GitHub.Api\NewTaskSystem\TaskBase.cs:406 
  at System.Threading.Tasks.Task`1[System.String].InvokeFuture (System.Object futureAsObj) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <filename unknown>:0 
   at GitHub.Unity.LogFacade.Trace(System.Exception ex, System.String message) in D:\code\github\Unity\src\GitHub.Logging\LogFacade.cs:line 91
   at GitHub.Unity.TaskManager+<ScheduleExclusive>c__AnonStorey1`1[[GitHub.Unity.TaskBase, GitHub.Api, Version=0.26.2.0, Culture=neutral, PublicKeyToken=null]].<>m__0(System.Threading.Tasks.Task tt) in D:\code\github\Unity\src\GitHub.Api\NewTaskSystem\TaskManager.cs:line 123
   at System.Threading.Tasks.Task+<>c__DisplayClass6.<ContinueWith>b__5(System.Object obj)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object obj)
   at System.Security.SecurityContext.Run(System.Security.SecurityContext securityContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Security/SecurityContext.cs:line 150
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.TaskScheduler.TryExecuteTask(System.Threading.Tasks.Task task)
   at GitHub.Unity.ConcurrentExclusiveInterleave+ConcurrentExclusiveTaskScheduler.ExecuteTask(System.Threading.Tasks.Task task) in D:\code\github\Unity\src\GitHub.Api\NewTaskSystem\ConcurrentExclusiveInterleave.cs:line 398
   at GitHub.Unity.ConcurrentExclusiveInterleave.ExecuteConcurrentTask(System.Threading.Tasks.Task task) in D:\code\github\Unity\src\GitHub.Api\NewTaskSystem\ConcurrentExclusiveInterleave.cs:line 214
   at System.Threading.Tasks.Parallel+<>c__DisplayClass32`2[[System.Threading.Tasks.Task, System.Threading, Version=1.0.3333.0, Culture=neutral, PublicKeyToken=402899b480e6f383],[System.Object, mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<PartitionerForEachWorker>b__30()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(System.Threading.Tasks.Task childTask)
   at System.Threading.Tasks.Task+<>c__DisplayClass3.<ExecuteSelfReplicating>b__2(System.Object )
   at System.Threading.Tasks.Task.ExecuteSelfReplicating(System.Threading.Tasks.Task root)
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object obj)
   at System.Security.SecurityContext.Run(System.Security.SecurityContext securityContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Security/SecurityContext.cs:line 150
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Reflection.MonoMethod.InternalInvoke(System.Object , System.Object[] , System.Exception ByRef )
```

**Comment by joehot200** [comment]
Thank you! It worked! Remind me to hug you later.

My main concern now is with the extra RAM used, however I will create another issue for that (along with comparisons between with and without git).

But anyway, this issue is now resolved, at least for me. Thank you for the support, I appreciate it.

**Comment by shana** [comment]
Great, thanks! The extra ram is worrying, yeah, an issue for that would be great.
