### ISSUE TITLE
Add better error output for Publish operations

### ISSUE THREAD

**Issue by StanleyGoldman** [github-for-unity/Unity#639]
### Repo already exists
![img](https://i.imgur.com/l0tQgtN.png)

```
180323-11:45:54.758 ERROR [ 1] <ApiClient>                         Error Creating Repository
GitHub.Unity.ApiClientException: 
  at GitHub.Unity.ApiClient+<CreateRepositoryInternal>c__asyncA.MoveNext () [0x003d1] in C:\Users\StanleyGoldman\Projects\GitHub\Unity\src\GitHub.Api\Application\ApiClient.cs:252 
=======
   at GitHub.Unity.ApiClient+<CreateRepositoryInternal>c__asyncA.MoveNext() in C:\Users\StanleyGoldman\Projects\GitHub\Unity\src\GitHub.Api\Application\ApiClient.cs:line 259
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
   at System.Runtime.CompilerServices.TaskAwaiter+<>c.<OnCompletedInternal>b__17_1(System.Object state)
   at UnityEditor.EditorApplication.Internal_CallDelayFunctions() in C:\buildslave\unity\build\artifacts\generated\common\editor\EditorApplicationBindings.gen.cs:line 259
180323-11:45:54.912 ERROR [ 1] <PublishView>                       Repository Create Error Type:GitHub.Unity.ApiClientException
GitHub.Unity.ApiClientException: 
HttpError: {"message":"Repository creation failed.","errors":[{"resource":"Repository","code":"custom","field":"name","message":"name already exists on this account"}],"documentation_url":"https://developer.github.com/v3/repos/#create"}
  at GitHub.Unity.ApiClient+<CreateRepositoryInternal>c__asyncA.MoveNext () [0x003d1] in C:\Users\StanleyGoldman\Projects\GitHub\Unity\src\GitHub.Api\Application\ApiClient.cs:252 
=======
   at GitHub.Unity.PublishView.<OnGUI>m__2(GitHub.Unity.GitHubRepository repository, System.Exception ex) in C:\Users\StanleyGoldman\Projects\GitHub\Unity\src\UnityExtension\Assets\Editor\GitHub.Unity\UI\PublishView.cs:line 169
   at GitHub.Unity.ApiClient+<CreateRepository>c__async2.MoveNext() in C:\Users\StanleyGoldman\Projects\GitHub\Unity\src\GitHub.Api\Application\ApiClient.cs:line 74
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object stateMachine)
   at System.Security.SecurityContext.Run(System.Security.SecurityContext securityContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Security/SecurityContext.cs:line 150
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Runtime.CompilerServices.TaskAwaiter+<>c.<OnCompletedInternal>b__17_1(System.Object state)
   at GitHub.Unity.MainThreadSynchronizationContext+<Post>c__AnonStorey1.<>m__0() in C:\Users\StanleyGoldman\Projects\GitHub\Unity\src\UnityExtension\Assets\Editor\GitHub.Unity\Threading\SingleThreadSynchronizationContext.cs:line 20
   at UnityEditor.EditorApplication.Internal_CallDelayFunctions() in C:\buildslave\unity\build\artifacts\generated\common\editor\EditorApplicationBindings.gen.cs:line 259
```

### Upgrade your plan
![img](https://i.imgur.com/eD77aWS.png)

```
180323-11:42:51.346 ERROR [ 1] <ApiClient>                         Error Creating Repository
GitHub.Unity.ApiClientException: 
HttpError: {"message":"Please upgrade your plan to create a new private repository.","documentation_url":"https://github.com/pricing"}
  at GitHub.Unity.ApiClient+<CreateRepositoryInternal>c__asyncA.MoveNext () [0x003d1] in C:\Users\StanleyGoldman\Projects\GitHub\Unity\src\GitHub.Api\Application\ApiClient.cs:252 
=======
   at GitHub.Unity.ApiClient+<CreateRepositoryInternal>c__asyncA.MoveNext() in C:\Users\StanleyGoldman\Projects\GitHub\Unity\src\GitHub.Api\Application\ApiClient.cs:line 259
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object stateMachine)
   at System.Security.SecurityContext.Run(System.Security.SecurityContext securityContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Security/SecurityContext.cs:line 150
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Runtime.CompilerServices.TaskAwaiter+<>c.<OnCompletedInternal>b__17_1(System.Object state)
   at GitHub.Unity.MainThreadSynchronizationContext+<Post>c__AnonStorey1.<>m__0() in C:\Users\StanleyGoldman\Projects\GitHub\Unity\src\UnityExtension\Assets\Editor\GitHub.Unity\Threading\SingleThreadSynchronizationContext.cs:line 20
   at UnityEditor.EditorApplication.Internal_CallDelayFunctions() in C:\buildslave\unity\build\artifacts\generated\common\editor\EditorApplicationBindings.gen.cs:line 259
180323-11:42:51.452 ERROR [ 1] <PublishView>                       Repository Create Error Type:GitHub.Unity.ApiClientException
GitHub.Unity.ApiClientException: 
HttpError: {"message":"Please upgrade your plan to create a new private repository.","documentation_url":"https://github.com/pricing"}
  at GitHub.Unity.ApiClient+<CreateRepositoryInternal>c__asyncA.MoveNext () [0x003d1] in C:\Users\StanleyGoldman\Projects\GitHub\Unity\src\GitHub.Api\Application\ApiClient.cs:252 
=======
   at GitHub.Unity.PublishView.<OnGUI>m__2(GitHub.Unity.GitHubRepository repository, System.Exception ex) in C:\Users\StanleyGoldman\Projects\GitHub\Unity\src\UnityExtension\Assets\Editor\GitHub.Unity\UI\PublishView.cs:line 169
   at GitHub.Unity.ApiClient+<CreateRepository>c__async2.MoveNext() in C:\Users\StanleyGoldman\Projects\GitHub\Unity\src\GitHub.Api\Application\ApiClient.cs:line 74
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object stateMachine)
   at System.Security.SecurityContext.Run(System.Security.SecurityContext securityContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Security/SecurityContext.cs:line 150
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Runtime.CompilerServices.TaskAwaiter+<>c.<OnCompletedInternal>b__17_1(System.Object state)
   at GitHub.Unity.MainThreadSynchronizationContext+<Post>c__AnonStorey1.<>m__0() in C:\Users\StanleyGoldman\Projects\GitHub\Unity\src\UnityExtension\Assets\Editor\GitHub.Unity\Threading\SingleThreadSynchronizationContext.cs:line 20
   at UnityEditor.EditorApplication.Internal_CallDelayFunctions() in C:\buildslave\unity\build\artifacts\generated\common\editor\EditorApplicationBindings.gen.cs:line 259
```

**Comment by StanleyGoldman** [comment]
![image](https://user-images.githubusercontent.com/417571/40180915-ec4e3744-59b5-11e8-81a3-975b223c7fa2.png)

**Comment by StanleyGoldman** [comment]
We definitely fixed this already
