### ISSUE TITLE
Commit Not Updating

### ISSUE THREAD

**Issue by sguthals** [github-for-unity/Unity#763]
### Steps to Reproduce

I did my first commit (assets/plugin) and it staged
I did a second commit of project settings and the UI in the commit section at the bottom seems to recognize that I committed it, but the Project Settings folder is still in the file changes at the top.
<img width="389" alt="screen shot 2018-05-16 at 1 19 17 pm" src="https://user-images.githubusercontent.com/1314285/40142123-a71a3000-590c-11e8-8ed8-c015d1bcb05e.png">
I then went to history and the commit wasn't there.
<img width="388" alt="screen shot 2018-05-16 at 1 20 23 pm" src="https://user-images.githubusercontent.com/1314285/40142126-a93b7f56-590c-11e8-80dd-7dc91e8bcb3b.png">
I went back to the changes tab and re-tried the commit and this time it worked.

### Additional Information
On Mac running Unity 5.6.0.f3

### Logs
```
180516-13:15:59.017  INFO [ 1] <Global>                            Initializing GitHubForUnity:'v0.35.0-beta' Unity:'v5.6.0f3'
180516-13:15:59.026 TRACE [ 2] <UsageTracker>                      userId:7ce52939-6f20-4bb0-b4ff-5aeee4608473 instanceId:d8e48d45-929e-49a6-9301-e5f8f4dbbbb2
180516-13:15:59.060 TRACE [ 3] <DownloadTask>                      Download of http://github-vs.s3.amazonaws.com/unity/latest.json to /Users/sarahguthals/Library/Application Support/GitHubUnity/latest.json Attempt 1 of 1
180516-13:15:59.089 TRACE [ 2] <ProcessWrapper>                    Running '/bin/bash -c "/usr/libexec/path_helper"'
180516-13:15:59.111 TRACE [ 3] <DownloadTask>                      Downloading http://github-vs.s3.amazonaws.com/unity/latest.json
180516-13:15:59.136 TRACE [ 2] <IApplicationManager>               Existing Environment Path Original:/usr/bin:/bin:/usr/sbin:/sbin Updated:PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Racket v6.8/bin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin"; export PATH;

180516-13:15:59.166  WARN [ 2] <OctorunInstaller>                  Current version 46811135 does not match expected 9fcd9faa
180516-13:15:59.179 TRACE [ 2] <UnzipTask>                         Unzip File: /Users/sarahguthals/Library/Application Support/GitHubUnity/downloads/octorun.zip to Path: /var/folders/tk/mrlhdh_9507_4_nz58bz3mjr0000gn/T/octorun_extract_archive_path_521668463
180516-13:15:59.285 TRACE [ 2] <ProcessWrapper>                    Running 'which git'
180516-13:15:59.321 TRACE [ 2] <ProcessWrapper>                    Running '/usr/local/bin/git --version'
180516-13:15:59.354 TRACE [ 2] <DownloadTask>                      Download of http://github-vs.s3.amazonaws.com/unity/git/mac/git-lfs.json to /Users/sarahguthals/Library/Application Support/GitHubUnity/git-lfs.json Attempt 1 of 1
180516-13:15:59.355 TRACE [ 2] <DownloadTask>                      Downloading http://github-vs.s3.amazonaws.com/unity/git/mac/git-lfs.json
180516-13:16:00.234 TRACE [ 2] <DownloadTask>                      Downloading http://github-vs.s3.amazonaws.com/unity/git/mac/git-lfs.json StatusCode:200
180516-13:16:00.241 TRACE [ 3] <DownloadTask>                      Downloading http://github-vs.s3.amazonaws.com/unity/latest.json StatusCode:200
180516-13:16:00.242 TRACE [ 2] <GitInstaller>                      /Users/sarahguthals/Library/Application Support/GitHubUnity/git-lfs/git-lfs is out of date
180516-13:16:00.249 TRACE [ 3] <Global>                            Skipping GitHub for Unity update v0.35.0-beta, we already have it
180516-13:16:00.262 TRACE [ 4] <DownloadTask>                      Download of http://ghfvs-installer.github.com/unity/git/mac/git-lfs.zip to /Users/sarahguthals/Library/Application Support/GitHubUnity/downloads/git-lfs.zip Attempt 1 of 1
180516-13:16:00.262 TRACE [ 4] <DownloadTask>                      Downloading http://ghfvs-installer.github.com/unity/git/mac/git-lfs.zip
180516-13:16:02.131 TRACE [ 4] <DownloadTask>                      Downloading http://ghfvs-installer.github.com/unity/git/mac/git-lfs.zip StatusCode:200
180516-13:16:03.004 TRACE [ 2] <UnzipTask>                         Unzip File: /Users/sarahguthals/Library/Application Support/GitHubUnity/downloads/git-lfs.zip to Path: /var/folders/tk/mrlhdh_9507_4_nz58bz3mjr0000gn/T/git_zip_extract_zip_paths_1475853434/git-lfs
180516-13:17:09.888 TRACE [ 1] <IApplicationManager>               Restarted null
180516-13:17:13.838 TRACE [ 1] <GitUserCache>                      needsInvalidation isInitialized:False timedOut:True
180516-13:17:13.847 TRACE [ 5] <ProcessWrapper>                    Running '/usr/local/bin/git config --get --global user.name'
180516-13:17:13.881 TRACE [ 9] <ProcessWrapper>                    Running '/usr/local/bin/git config --get --global user.email'
180516-13:17:14.102 TRACE [ 1] <GitUserCache>                      05/16/2018 13:17:14 -07:00 Updating Name: current: new:sguthals
180516-13:17:14.104 TRACE [ 1] <GitUserCache>                      05/16/2018 13:17:14 -07:00 Updating Email: current: new:sarah@guthals.com
180516-13:17:15.503 TRACE [14] <ProcessWrapper>                    Running '/usr/local/bin/git init'
180516-13:17:15.548 TRACE [14] <ProcessWrapper>                    Running '/usr/local/bin/git config --replace-all --local merge.unityyamlmerge.cmd "'/Applications/Unity/Unity.app/Contents/Tools/UnityYAMLMerge' merge -p '$BASE' '$REMOTE' '$LOCAL' '$MERGED'"'
180516-13:17:15.573 TRACE [14] <ProcessWrapper>                    Running '/usr/local/bin/git config --replace-all --local merge.unityyamlmerge.trustExitCode "false"'
180516-13:17:15.600 TRACE [14] <ProcessWrapper>                    Running '/usr/local/bin/git lfs install'
180516-13:17:15.694 TRACE [14] <ProcessWrapper>                    Running '/usr/local/bin/git add  --  "/Users/sarahguthals/Game 12/.gitignore" "/Users/sarahguthals/Game 12/.gitattributes" "/Users/sarahguthals/Game 12/Assets/.gitignore"'
180516-13:17:15.725 TRACE [14] <ProcessWrapper>                    Running '/usr/local/bin/git -c i18n.commitencoding=utf8 commit --file "/var/folders/tk/mrlhdh_9507_4_nz58bz3mjr0000gn/T/GitCommitTask_1424709032"'
180516-13:17:15.820 TRACE [ 1] <GitLogCache>                       needsInvalidation isInitialized:False timedOut:True
180516-13:17:15.826 TRACE [ 1] <GitAheadBehindCache>               needsInvalidation isInitialized:False timedOut:True
180516-13:17:15.836 TRACE [ 1] <RepositoryInfoCache>               needsInvalidation isInitialized:False timedOut:True
180516-13:17:15.843 TRACE [14] <RepositoryWatcher>                 Watching Path: "/Users/sarahguthals/Game 12"
180516-13:17:15.867 TRACE [15] <ProcessWrapper>                    Running '/usr/local/bin/git git log'
180516-13:17:15.923 TRACE [14] <IApplicationManager>               Got a repository? /Users/sarahguthals/Game 12
180516-13:17:15.934 TRACE [ 1] <GitAheadBehindCache>               05/16/2018 13:17:15 -07:00 Updating Ahead: current:0 new:0
180516-13:17:15.935 TRACE [ 1] <GitAheadBehindCache>               05/16/2018 13:17:15 -07:00 Updating Behind: current:0 new:0
180516-13:17:15.941 TRACE [ 1] <IApplicationManager>               Restarted /Users/sarahguthals/Game 12
180516-13:17:15.944 TRACE [ 1] <GitLocksCache>                     needsInvalidation isInitialized:False timedOut:True
180516-13:17:15.948 TRACE [ 1] <GitStatusCache>                    needsInvalidation isInitialized:False timedOut:True
180516-13:17:15.961 TRACE [ 1] <GitLogCache>                       05/16/2018 13:17:15 -07:00 Updating Log: current:0 new:1
180516-13:17:15.961 TRACE [18] <ProcessWrapper>                    Running '/usr/local/bin/git -c i18n.logoutputencoding=utf8 -c core.quotepath=false status -b -u --porcelain'
180516-13:17:16.138 TRACE [ 1] <GitStatusCache>                    05/16/2018 13:17:16 -07:00 Updating Entries: current:0 new:61
180516-13:17:16.364 TRACE [ 1] <GitAheadBehindCache>               05/16/2018 13:17:16 -07:00 Updating Ahead: current:0 new:0
180516-13:17:16.376 TRACE [ 1] <GitAheadBehindCache>               05/16/2018 13:17:16 -07:00 Updating Behind: current:0 new:0
180516-13:17:16.922 TRACE [22] <ProcessWrapper>                    Running '/usr/local/bin/git -c i18n.logoutputencoding=utf8 -c core.quotepath=false status -b -u --porcelain'
180516-13:17:17.073 TRACE [ 1] <GitStatusCache>                    05/16/2018 13:17:17 -07:00 Updating Entries: current:61 new:61
180516-13:17:17.076 TRACE [ 1] <GitAheadBehindCache>               05/16/2018 13:17:17 -07:00 Updating Ahead: current:0 new:0
180516-13:17:17.077 TRACE [ 1] <GitAheadBehindCache>               05/16/2018 13:17:17 -07:00 Updating Behind: current:0 new:0
180516-13:17:17.989 TRACE [18] <ProcessWrapper>                    Running '/usr/local/bin/git -c i18n.logoutputencoding=utf8 -c core.quotepath=false status -b -u --porcelain'
180516-13:17:18.141 TRACE [ 1] <GitStatusCache>                    05/16/2018 13:17:18 -07:00 Updating Entries: current:61 new:61
180516-13:17:18.144 TRACE [ 1] <GitAheadBehindCache>               05/16/2018 13:17:18 -07:00 Updating Ahead: current:0 new:0
180516-13:17:18.145 TRACE [ 1] <GitAheadBehindCache>               05/16/2018 13:17:18 -07:00 Updating Behind: current:0 new:0
180516-13:17:36.104 TRACE [22] <ProcessWrapper>                    Running '/usr/local/bin/git add  --  "Assets/Plugins.meta" "Assets/Plugins/GitHub.meta" "Assets/Plugins/GitHub/Editor.meta" "Assets/Plugins/GitHub/Editor/AsyncBridge.Net35.dll" "Assets/Plugins/GitHub/Editor/AsyncBridge.Net35.dll.meta" "Assets/Plugins/GitHub/Editor/CREDITS.txt" "Assets/Plugins/GitHub/Editor/CREDITS.txt.meta" "Assets/Plugins/GitHub/Editor/EULA.txt" "Assets/Plugins/GitHub/Editor/EULA.txt.meta" "Assets/Plugins/GitHub/Editor/GitHub.Api.dll" "Assets/Plugins/GitHub/Editor/GitHub.Api.dll.mdb" "Assets/Plugins/GitHub/Editor/GitHub.Api.dll.mdb.meta" "Assets/Plugins/GitHub/Editor/GitHub.Api.dll.meta" "Assets/Plugins/GitHub/Editor/GitHub.Logging.dll" "Assets/Plugins/GitHub/Editor/GitHub.Logging.dll.mdb" "Assets/Plugins/GitHub/Editor/GitHub.Logging.dll.mdb.meta" "Assets/Plugins/GitHub/Editor/GitHub.Logging.dll.meta" "Assets/Plugins/GitHub/Editor/GitHub.Unity.dll" "Assets/Plugins/GitHub/Editor/GitHub.Unity.dll.mdb" "Assets/Plugins/GitHub/Editor/GitHub.Unity.dll.mdb.meta" "Assets/Plugins/GitHub/Editor/GitHub.Unity.dll.meta" "Assets/Plugins/GitHub/Editor/ICSharpCode.SharpZipLib.dll" "Assets/Plugins/GitHub/Editor/ICSharpCode.SharpZipLib.dll.meta" "Assets/Plugins/GitHub/Editor/libsfw.bundle" "Assets/Plugins/GitHub/Editor/libsfw.bundle.meta" "Assets/Plugins/GitHub/Editor/libsfw.so" "Assets/Plugins/GitHub/Editor/libsfw.so.meta" "Assets/Plugins/GitHub/Editor/Mono.Posix.dll" "Assets/Plugins/GitHub/Editor/Mono.Posix.dll.meta" "Assets/Plugins/GitHub/Editor/ReadOnlyCollectionsInterfaces.dll" "Assets/Plugins/GitHub/Editor/ReadOnlyCollectionsInterfaces.dll.meta" "Assets/Plugins/GitHub/Editor/sfw.net.dll" "Assets/Plugins/GitHub/Editor/sfw.net.dll.meta" "Assets/Plugins/GitHub/Editor/System.Threading.dll" "Assets/Plugins/GitHub/Editor/System.Threading.dll.meta" "Assets/Plugins/GitHub/Editor/x64.meta" "Assets/Plugins/GitHub/Editor/x64/pthreadVC2.dll" "Assets/Plugins/GitHub/Editor/x64/pthreadVC2.dll.meta" "Assets/Plugins/GitHub/Editor/x64/sfw_x64.dll" "Assets/Plugins/GitHub/Editor/x64/sfw_x64.dll.meta" "Assets/Plugins/GitHub/Editor/x86.meta" "Assets/Plugins/GitHub/Editor/x86/pthreadVC2.dll" "Assets/Plugins/GitHub/Editor/x86/pthreadVC2.dll.meta" "Assets/Plugins/GitHub/Editor/x86/sfw_x86.dll" "Assets/Plugins/GitHub/Editor/x86/sfw_x86.dll.meta"'
180516-13:17:36.236 TRACE [22] <ProcessWrapper>                    Running '/usr/local/bin/git -c i18n.commitencoding=utf8 commit --file "/var/folders/tk/mrlhdh_9507_4_nz58bz3mjr0000gn/T/GitCommitTask_1415130961"'
180516-13:17:36.538 TRACE [ 1] <RepositoryWatcher>                 Watching Path: "/Users/sarahguthals/Game 12"
180516-13:17:36.699 TRACE [ 1] <BranchesCache>                     needsInvalidation isInitialized:False timedOut:True
180516-13:17:36.705 TRACE [28] <ProcessWrapper>                    Running '/usr/local/bin/git git log'
180516-13:17:36.707 TRACE [21] <ProcessWrapper>                    Running '/usr/local/bin/git -c i18n.logoutputencoding=utf8 -c core.quotepath=false status -b -u --porcelain'
180516-13:17:36.855 TRACE [ 1] <GitAheadBehindCache>               05/16/2018 13:17:36 -07:00 Updating Ahead: current:0 new:0
180516-13:17:36.856 TRACE [ 1] <GitAheadBehindCache>               05/16/2018 13:17:36 -07:00 Updating Behind: current:0 new:0
180516-13:17:36.857 TRACE [ 1] <GitAheadBehindCache>               05/16/2018 13:17:36 -07:00 Updating Ahead: current:0 new:0
180516-13:17:36.858 TRACE [ 1] <GitAheadBehindCache>               05/16/2018 13:17:36 -07:00 Updating Behind: current:0 new:0
180516-13:17:36.860 TRACE [ 1] <GitLogCache>                       05/16/2018 13:17:36 -07:00 Updating Log: current:1 new:2
180516-13:17:36.864 TRACE [ 1] <GitStatusCache>                    05/16/2018 13:17:36 -07:00 Updating Entries: current:61 new:16
180516-13:17:36.865 TRACE [ 1] <GitAheadBehindCache>               05/16/2018 13:17:36 -07:00 Updating Ahead: current:0 new:0
180516-13:17:36.866 TRACE [ 1] <GitAheadBehindCache>               05/16/2018 13:17:36 -07:00 Updating Behind: current:0 new:0
180516-13:17:47.975 TRACE [33] <ProcessWrapper>                    Running '/usr/local/bin/git add -A'
180516-13:17:48.007 TRACE [33] <ProcessWrapper>                    Running '/usr/local/bin/git -c i18n.commitencoding=utf8 commit --file "/var/folders/tk/mrlhdh_9507_4_nz58bz3mjr0000gn/T/GitCommitTask_1637798820"'
180516-13:17:48.054 ERROR [34] <TaskManager>                       Exception on exclusive thread: 1 -c i18n.commitencoding=utf8 commit --file "/var/folders/tk/mrlhdh_9507_4_nz58bz3mjr0000gn/T/GitCommitTask_1637798820"
GitHub.Unity.ProcessException: Aborting commit due to empty commit message.
  at GitHub.Unity.ProcessTask`1+<RunWithReturn>c__AnonStorey0[System.String].<>m__0 () [0x0013e] in /Users/shana/code/work/github/Unity/src/GitHub.Api/Tasks/ProcessTask.cs:327 
  at GitHub.Unity.ProcessWrapper.Run () [0x003de] in /Users/shana/code/work/github/Unity/src/GitHub.Api/Tasks/ProcessTask.cs:189 
  at GitHub.Unity.ProcessTask`1[T].RunWithReturn (Boolean success) [0x00062] in /Users/shana/code/work/github/Unity/src/GitHub.Api/Tasks/ProcessTask.cs:341 
  at GitHub.Unity.TaskBase`1[TResult].<TaskBase>m__0 () [0x0005d] in /Users/shana/code/work/github/Unity/src/GitHub.Api/Tasks/TaskBase.cs:524 
  at System.Threading.Tasks.Task`1[System.String].InvokeFuture (System.Object futureAsObj) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <filename unknown>:0 
=======
   at GitHub.Unity.TaskManager+<ScheduleExclusive>c__AnonStorey1`1[[GitHub.Unity.TaskBase, GitHub.Api, Version=0.35.0.0, Culture=neutral, PublicKeyToken=null]].<>m__0(System.Threading.Tasks.Task tt) in /Users/shana/code/work/github/Unity/src/GitHub.Api/Tasks/TaskManager.cs:line 109
   at System.Threading.Tasks.Task+<>c__DisplayClass6.<ContinueWith>b__5(System.Object obj)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object obj)
   at System.Security.SecurityContext.Run(System.Security.SecurityContext securityContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Security/SecurityContext.cs:line 150
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.TaskScheduler.TryExecuteTask(System.Threading.Tasks.Task task)
   at GitHub.Unity.ThreadPerTaskScheduler+<QueueTask>c__AnonStorey0.<>m__0() in /Users/shana/code/work/github/Unity/src/GitHub.Api/Tasks/ConcurrentExclusiveInterleave.cs:line 440
180516-13:17:48.245 TRACE [ 1] <RepositoryWatcher>                 Watching Path: "/Users/sarahguthals/Game 12"
180516-13:17:48.398 TRACE [27] <ProcessWrapper>                    Running '/usr/local/bin/git -c i18n.logoutputencoding=utf8 -c core.quotepath=false status -b -u --porcelain'
180516-13:17:48.398 TRACE [35] <ProcessWrapper>                    Running '/usr/local/bin/git git log'
180516-13:17:48.549 TRACE [ 1] <GitStatusCache>                    05/16/2018 13:17:48 -07:00 Updating Entries: current:16 new:16
180516-13:17:48.551 TRACE [ 1] <GitAheadBehindCache>               05/16/2018 13:17:48 -07:00 Updating Ahead: current:0 new:0
180516-13:17:48.552 TRACE [ 1] <GitAheadBehindCache>               05/16/2018 13:17:48 -07:00 Updating Behind: current:0 new:0
180516-13:17:48.553 TRACE [ 1] <GitLogCache>                       05/16/2018 13:17:48 -07:00 Updating Log: current:2 new:2
180516-13:20:20.685 TRACE [ 1] <GitLogCache>                       needsInvalidation isInitialized:True timedOut:True
180516-13:20:20.686 TRACE [40] <ProcessWrapper>                    Running '/usr/local/bin/git git log'
180516-13:20:20.686 TRACE [ 1] <GitAheadBehindCache>               needsInvalidation isInitialized:True timedOut:True
180516-13:20:20.709 TRACE [ 1] <GitAheadBehindCache>               05/16/2018 13:20:20 -07:00 Updating Ahead: current:0 new:0
180516-13:20:20.714 TRACE [ 1] <GitAheadBehindCache>               05/16/2018 13:20:20 -07:00 Updating Behind: current:0 new:0
180516-13:20:20.862 TRACE [ 1] <GitLogCache>                       05/16/2018 13:20:20 -07:00 Updating Log: current:2 new:2
180516-13:20:50.668 TRACE [ 1] <GitStatusCache>                    needsInvalidation isInitialized:True timedOut:True
180516-13:20:50.669 TRACE [43] <ProcessWrapper>                    Running '/usr/local/bin/git -c i18n.logoutputencoding=utf8 -c core.quotepath=false status -b -u --porcelain'
180516-13:20:50.723 TRACE [ 1] <GitStatusCache>                    05/16/2018 13:20:50 -07:00 Updating Entries: current:16 new:16
180516-13:20:50.725 TRACE [ 1] <GitAheadBehindCache>               05/16/2018 13:20:50 -07:00 Updating Ahead: current:0 new:0
180516-13:20:50.726 TRACE [ 1] <GitAheadBehindCache>               05/16/2018 13:20:50 -07:00 Updating Behind: current:0 new:0
180516-13:20:54.117 TRACE [27] <ProcessWrapper>                    Running '/usr/local/bin/git add -A'
180516-13:20:54.145 TRACE [27] <ProcessWrapper>                    Running '/usr/local/bin/git -c i18n.commitencoding=utf8 commit --file "/var/folders/tk/mrlhdh_9507_4_nz58bz3mjr0000gn/T/GitCommitTask_1751161720"'
180516-13:20:54.522 TRACE [ 1] <RepositoryWatcher>                 Watching Path: "/Users/sarahguthals/Game 12"
180516-13:20:54.675 TRACE [47] <ProcessWrapper>                    Running '/usr/local/bin/git git log'
180516-13:20:54.677 TRACE [21] <ProcessWrapper>                    Running '/usr/local/bin/git -c i18n.logoutputencoding=utf8 -c core.quotepath=false status -b -u --porcelain'
180516-13:20:54.828 TRACE [ 1] <GitAheadBehindCache>               05/16/2018 13:20:54 -07:00 Updating Ahead: current:0 new:0
180516-13:20:54.829 TRACE [ 1] <GitAheadBehindCache>               05/16/2018 13:20:54 -07:00 Updating Behind: current:0 new:0
180516-13:20:54.830 TRACE [ 1] <GitAheadBehindCache>               05/16/2018 13:20:54 -07:00 Updating Ahead: current:0 new:0
180516-13:20:54.831 TRACE [ 1] <GitAheadBehindCache>               05/16/2018 13:20:54 -07:00 Updating Behind: current:0 new:0
180516-13:20:54.832 TRACE [ 1] <GitLogCache>                       05/16/2018 13:20:54 -07:00 Updating Log: current:2 new:3
180516-13:20:54.834 TRACE [ 1] <GitStatusCache>                    05/16/2018 13:20:54 -07:00 Updating Entries: current:16 new:0
180516-13:20:54.835 TRACE [ 1] <GitAheadBehindCache>               05/16/2018 13:20:54 -07:00 Updating Ahead: current:0 new:0
180516-13:20:54.836 TRACE [ 1] <GitAheadBehindCache>               05/16/2018 13:20:54 -07:00 Updating Behind: current:0 new:0
```

**Comment by StanleyGoldman** [comment]
@sguthals Are you still able to reproduce this issue?

**Comment by StanleyGoldman** [comment]
I'm closing this for now.
