### ISSUE TITLE
Commit Exception on "removed" item

### ISSUE THREAD

**Issue by ThomasAunvik** [github-for-unity/Unity#783]
### Prerequisites

[Log File](https://gist.github.com/ThomasAunvik/3d834ac00dd7e64b3f609a8699baf1ee)

### Description

```
System.NullReferenceException: A null value was found where an object instance was required.
  at <0x00000> <unknown method>
  at GitHub.Unity.ChangesView.<Commit>b__46_0 (Boolean success, System.Exception exception) [0x00000] in <filename unknown>:0 
  at GitHub.Unity.ActionTask.Run (Boolean success) [0x00000] in <filename unknown>:0 
=======
   at GitHub.Unity.TaskManager+<>c__DisplayClass28_0`1[[GitHub.Unity.TaskBase, GitHub.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<ScheduleUI>b__0(System.Threading.Tasks.Task tt)
   at System.Threading.Tasks.Task+<>c__DisplayClass6.<ContinueWith>b__5(System.Object obj)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object obj)
   at System.Security.SecurityContext.Run(System.Security.SecurityContext securityContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Security/SecurityContext.cs:line 150
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.TaskScheduler.TryExecuteTask(System.Threading.Tasks.Task task)
   at GitHub.Unity.ThreadPerTaskScheduler+<>c__DisplayClass4_0.<QueueTask>b__0()
```

This happens when i try to commit a "deleted" file which is not deleted, it shows that the commit is pushed, but it is not. The changeview is also disabled. Push button is also disabled.

Tested on branch: https://github.com/ThomasAunvik/Github-For-Unity/tree/c5d27a6b7d623789fd66e65db9b0be94a269ca7f

![image](https://user-images.githubusercontent.com/9968151/40319895-2441c8f6-5d2a-11e8-8f78-4b3f32553422.png)
![image](https://user-images.githubusercontent.com/9968151/40319910-307ce0a6-5d2a-11e8-9d27-da10a08a192f.png)

Im also getting this error when i relaunched:
```19:10:15 PM [ 2] <IApplicationManager> A problem ocurred setting up Git
UnityEngine.UnityException: CreateScriptableObjectInstanceFromType can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
  at (wrapper managed-to-native) UnityEngine.ScriptableObject:CreateScriptableObjectInstanceFromType (System.Type)
  at UnityEngine.ScriptableObject.CreateInstance (System.Type type) [0x00002] in C:\buildslave\unity\build\Runtime\Export\ScriptableObject.bindings.cs:33 
  at UnityEngine.ScriptableObject.CreateInstance[EnvironmentCache] () [0x0000b] in C:\buildslave\unity\build\Runtime\Export\ScriptableObject.bindings.cs:39 
  at GitHub.Unity.ScriptObjectSingleton`1[GitHub.Unity.EnvironmentCache].CreateAndLoad () [0x00000] in <filename unknown>:0 
  at GitHub.Unity.ScriptObjectSingleton`1[GitHub.Unity.EnvironmentCache].get_Instance () [0x00000] in <filename unknown>:0 
  at GitHub.Unity.ApplicationManager.get_Environment () [0x00000] in <filename unknown>:0 
  at GitHub.Unity.ApplicationManagerBase.RestartRepository () [0x00000] in <filename unknown>:0 
  at GitHub.Unity.ApplicationManagerBase.<Run>b__20_0 () [0x00000] in <filename unknown>:0 
=======
   at GitHub.Unity.ApplicationManagerBase.<Run>b__20_0()
UnityEngine.Debug:LogError(Object)
GitHub.Unity.UnityLogAdapter:Error(String, String)
GitHub.Logging.MultipleLogAdapter:Error(String, String)
GitHub.Logging.LogFacade:Error(String)
GitHub.Logging.LogFacade:Error(Exception, String)
GitHub.Unity.ApplicationManagerBase:<Run>b__20_0()
```

```
CreateScriptableObjectInstanceFromType can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
UnityEngine.ScriptableObject:CreateInstance()
GitHub.Unity.ScriptObjectSingleton`1:CreateAndLoad()
GitHub.Unity.ScriptObjectSingleton`1:get_Instance()
GitHub.Unity.ApplicationManager:get_Environment()
GitHub.Unity.ApplicationManagerBase:RestartRepository()
GitHub.Unity.ApplicationManagerBase:<Run>b__20_0()
```

Apparently even Github Desktop can even make the same mistake, thinking it is a Git issue.

![image](https://user-images.githubusercontent.com/9968151/40320381-cebee330-5d2b-11e8-8e9f-767b5515e7c6.png)

### Steps to Reproduce

1. Relaunch Unity when after build finished
2. Select the "deleted" file
3. Commit

**Expected behavior:** To not give out error

**Actual behavior:** Gives out error and blocks basic features.

**Reproduces how often:** Unsure

### Additional Information

Have the same broken pc as i do.

**Comment by ThomasAunvik** [comment]
Github for Desktop wants me to publish the branch, cant even push...
![image](https://user-images.githubusercontent.com/9968151/40320463-1a4e05a6-5d2c-11e8-81f8-e051d0fdb33c.png)

**Comment by ThomasAunvik** [comment]
Wanted me to pull and push, did not want to pull, so i needed to undo commits, then again commit all, then commit -f. Then it worked.

Still have the issue till day.

**Comment by ThomasAunvik** [comment]
Tried on master branch, still happening, now getting this error:
```
NullReferenceException: Object reference not set to an instance of an object
GitHub.Unity.ChangesView.<BuildTree>b__42_0 (GitStatusEntry entry)
System.Linq.Enumerable+<CreateSelectIterator>c__Iterator10`2[GitHub.Unity.GitStatusEntry,GitHub.Unity.GitStatusEntryTreeData].MoveNext ()
GitHub.Unity.TreeBase`2[GitHub.Unity.ChangesTreeNode,GitHub.Unity.GitStatusEntryTreeData].Load (IEnumerable`1 treeDatas)
GitHub.Unity.ChangesView.BuildTree ()
GitHub.Unity.ChangesView.MaybeUpdateData ()
GitHub.Unity.ChangesView.OnDataUpdate ()
GitHub.Unity.Window.SwitchView (GitHub.Unity.Subview fromView, GitHub.Unity.Subview toView)
GitHub.Unity.Window.UpdateActiveTab ()
GitHub.Unity.Window.DoToolbarGUI ()
GitHub.Unity.Window.OnUI ()
GitHub.Unity.BaseWindow.OnGUI ()
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:291)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:284)
UnityEditor.HostView.InvokeOnGUI (Rect onGUIPosition) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:251)
```

**Comment by shana** [comment]
@ThomasAunvik What are the steps to reproduce this, exactly? You deleted the .gitignore file and committed it?

**Comment by ThomasAunvik** [comment]
No, i did not delete it, but it shows as deleted, git shows that too. Its probably some weird git bug when it comes to this. I will check on it.

I deleted the .gitignore file and re-added it with the generate .gitignore button i created. And then i commited.

**Comment by ThomasAunvik** [comment]
Here are some videos and logs on how this happened.

[Original Bug Video](https://drive.google.com/file/d/1wlz21wsKOZvID8My6cc7ZYbT4I8-QXWu/view?usp=sharing)
[Original Bug Log](https://gist.github.com/ThomasAunvik/7b7bc77cfbe8376c9102d7fbd9de7ac0)

[Initialization Bug Video](https://drive.google.com/file/d/1rmSXM_ycgOTv0uyXLLQF5pdNH82VvPfd/view?usp=sharing)
[Initialization Bug Log](https://gist.github.com/ThomasAunvik/ce28ce50cbe26fd678bc85e0b38ff1a3)

**Comment by StanleyGoldman** [comment]
@ThomasAunvik is this issue still around?

**Comment by ThomasAunvik** [comment]
No, i do not think so.
