### ISSUE TITLE
Can't sign in on Linux

### ISSUE THREAD

**Issue by TheKrane** [github-for-unity/Unity#853]
Whenever I try to sign in on Linux on the newest Unity build (2018.1.5f1) I get the following error message:

> `180629-20:06:06.063  INFO [ 1] <Global>                            Initializing GitHubForUnity:'v1.0.0' Unity:'v2018.1.5f1'
180629-20:09:09.507 ERROR [ 6] <TaskManager>                       Exception on concurrent thread: 1 FuncTask<GitHub.Unity.GitHubUser>
GitHub.Unity.KeychainEmptyException: Exception of type 'GitHub.Unity.KeychainEmptyException' was thrown.
  at GitHub.Unity.ApiClient.GetCurrentUser () [0x0001d] in /Users/shana/code/work/github/Unity/src/GitHub.Api/Application/ApiClient.cs:214 
  at GitHub.Unity.FuncTask`1+<FuncTask>c__AnonStorey0[GitHub.Unity.GitHubUser].<>m__0 (Boolean _) [0x00000] in /Users/shana/code/work/github/Unity/src/GitHub.Api/Tasks/ActionTask.cs:395 
  at GitHub.Unity.FuncTask`1[GitHub.Unity.GitHubUser].RunWithReturn (Boolean success) [0x00013] in /Users/shana/code/work/github/Unity/src/GitHub.Api/Tasks/ActionTask.cs:422 
=======
   at GitHub.Unity.TaskManager+<ScheduleConcurrent>c__AnonStorey2`1[[GitHub.Unity.TaskBase, GitHub.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<>m__0(System.Threading.Tasks.Task tt) in /Users/shana/code/work/github/Unity/src/GitHub.Api/Tasks/TaskManager.cs:line 134
   at System.Threading.Tasks.Task+<>c__DisplayClass6.<ContinueWith>b__5(System.Object obj)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object obj)
   at System.Security.SecurityContext.Run(System.Security.SecurityContext securityContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Security/SecurityContext.cs:line 150
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.TaskScheduler.TryExecuteTask(System.Threading.Tasks.Task task)
   at GitHub.Unity.ThreadPerTaskScheduler+<QueueTask>c__AnonStorey0.<>m__0() in /Users/shana/code/work/github/Unity/src/GitHub.Api/Tasks/ConcurrentExclusiveInterleave.cs:line 440
180629-20:09:28.982  WARN [ 7] <LoginManager>                      Login Exception
GitHub.Unity.ProcessException: Error code -42
File name has not been set
' config --get-all credential.helper'
DESKTOP_AUTOSTART_ID:10b096b36b84c9014a153011171732576900000018250007
XDG_SESSION_TYPE:x11
XDG_RUNTIME_DIR:/run/user/1000
GPG_AGENT_INFO:/run/user/1000/gnupg/S.gpg-agent:0:1
GHU_WORKINGDIR:/home/christopher/Documents/Projects/Gridiron
XDG_SESSION_ID:1
OLDPWD:/home/christopher
TEXTDOMAINDIR:/usr/share/locale/
VTE_VERSION:5201
TEMP:/tmp
COLORTERM:truecolor
XDG_DATA_DIRS:/usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop
DEVKITARM:/opt/devkitpro/devkitARM
GNOME_TERMINAL_SCREEN:/org/gnome/Terminal/screen/c63d393f_5e52_45c8_892e_51ce63ae4f54
GTK_IM_MODULE:ibus
SHLVL:1
LC_ADDRESS:de_AT.UTF-8
IM_CONFIG_PHASE:2
XDG_CURRENT_DESKTOP:ubuntu:GNOME
LC_PAPER:de_AT.UTF-8
TEXTDOMAIN:im-config
XDG_VTNR:1
MANDATORY_PATH:/usr/share/gconf/ubuntu.mandatory.path
XDG_SESSION_DESKTOP:ubuntu
WINDOWPATH:1
LC_MEASUREMENT:de_AT.UTF-8
XDG_MENU_PREFIX:gnome-
XDG_SEAT:seat0
TMP:/tmp
LC_MONETARY:de_AT.UTF-8
DEFAULTS_PATH:/usr/share/gconf/ubuntu.default.path
HOME:/home/christopher
DISPLAY:0
LESSCLOSE:/usr/bin/lesspipe %s %s
SSH_AGENT_PID:1933
LANG:en_US.UTF-8
TERM:xterm-256color
PATH:END:/home/christopher/.local/bin:/opt/devkitpro/tools/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
LC_NAME:de_AT.UTF-8
GHU_FULLPATH:END:/home/christopher/.local/bin:/opt/devkitpro/tools/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
XAUTHORITY:/run/user/1000/gdm/Xauthority
LC_NUMERIC:de_AT.UTF-8
CLUTTER_IM_MODULE:xim
GNOME_SHELL_SESSION_MODE:ubuntu
GDMSESSION:ubuntu
LOGNAME:christopher
USER:christopher
DESKTOP_SESSION:ubuntu
PWD:/home/christopher/Downloads
LC_IDENTIFICATION:de_AT.UTF-8
SHELL:/bin/bash
XDG_CONFIG_DIRS:/etc/xdg/xdg-ubuntu:/etc/xdg
SESSION_MANAGER:local/Cosmos:@/tmp/.ICE-unix/1825,unix/Cosmos:/tmp/.ICE-unix/1825
QT_IM_MODULE:ibus
DBUS_SESSION_BUS_ADDRESS:unix:path=/run/user/1000/bus
LESSOPEN:| /usr/bin/lesspipe %s
GITLFSLOCKSENABLED:1
GNOME_DESKTOP_SESSION_ID:this-is-deprecated
SSH_AUTH_SOCK:/run/user/1000/keyring/ssh
LC_TELEPHONE:de_AT.UTF-8
QT_ACCESSIBILITY:1
GTK_MODULES:gail:atk-bridge
LC_TIME:de_AT.UTF-8
XMODIFIERS:@im=ibus
DEVKITPRO:/opt/devkitpro
GNOME_TERMINAL_SERVICE::1.1625
_:./UnitySetup-2018.1.5f1
DEVKITPPC:/opt/devkitpro/devkitPPC
LS_COLORS:rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
QT4_IM_MODULE:xim
USERNAME:christopher
 ---> System.InvalidOperationException: File name has not been set
  at System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process) [0x00000] in <filename unknown>:0 
  at System.Diagnostics.Process.Start () [0x00000] in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process:Start ()
  at GitHub.Unity.ProcessWrapper.Run () [0x000c1] in /Users/shana/code/work/github/Unity/src/GitHub.Api/Tasks/ProcessTask.cs:137 
  --- End of inner exception stack trace ---
  at GitHub.Unity.ProcessTask`1+<RunWithReturn>c__AnonStorey0[System.String].<>m__1 () [0x0013e] in /Users/shana/code/work/github/Unity/src/GitHub.Api/Tasks/ProcessTask.cs:371 
  at GitHub.Unity.ProcessWrapper.Run () [0x00424] in /Users/shana/code/work/github/Unity/src/GitHub.Api/Tasks/ProcessTask.cs:199 
  at GitHub.Unity.ProcessTask`1[T].RunWithReturn (Boolean success) [0x00061] in /Users/shana/code/work/github/Unity/src/GitHub.Api/Tasks/ProcessTask.cs:380 
  at GitHub.Unity.TaskBase`1[TResult].RunSynchronously () [0x0007c] in /Users/shana/code/work/github/Unity/src/GitHub.Api/Tasks/TaskBase.cs:685 
  at GitHub.Unity.GitCredentialManager.LoadCredentialHelper () [0x0000d] in /Users/shana/code/work/github/Unity/src/GitHub.Api/Git/GitCredentialManager.cs:122 
  at GitHub.Unity.GitCredentialManager.Delete (GitHub.Unity.UriString host) [0x00000] in /Users/shana/code/work/github/Unity/src/GitHub.Api/Git/GitCredentialManager.cs:33 
  at GitHub.Unity.Keychain.AddCredential (GitHub.Unity.UriString host) [0x00028] in /Users/shana/code/work/github/Unity/src/GitHub.Api/Authentication/Keychain.cs:242 
  at GitHub.Unity.Keychain.Save (GitHub.Unity.UriString host) [0x0000b] in /Users/shana/code/work/github/Unity/src/GitHub.Api/Authentication/Keychain.cs:158 
  at GitHub.Unity.LoginManager.Login (GitHub.Unity.UriString host, System.String username, System.String password) [0x000b4] in /Users/shana/code/work/github/Unity/src/GitHub.Api/Authentication/LoginManager.cs:83 
System.InvalidOperationException: File name has not been set
  at System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process) [0x00000] in <filename unknown>:0 
  at System.Diagnostics.Process.Start () [0x00000] in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process:Start ()
  at GitHub.Unity.ProcessWrapper.Run () [0x000c1] in /Users/shana/code/work/github/Unity/src/GitHub.Api/Tasks/ProcessTask.cs:137 
=======
   at GitHub.Unity.LoginManager.Login(GitHub.Unity.UriString host, System.String username, System.String password) in /Users/shana/code/work/github/Unity/src/GitHub.Api/Authentication/LoginManager.cs:line 93
   at GitHub.Unity.ApiClient+<Login>c__AnonStorey3.<>m__0() in /Users/shana/code/work/github/Unity/src/GitHub.Api/Application/ApiClient.cs:line 166
   at GitHub.Unity.FuncTask`1+<FuncTask>c__AnonStorey0[[GitHub.Unity.LoginResultData, GitHub.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<>m__0(Boolean _) in /Users/shana/code/work/github/Unity/src/GitHub.Api/Tasks/ActionTask.cs:line 395
   at GitHub.Unity.FuncTask`1[[GitHub.Unity.LoginResultData, GitHub.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].RunWithReturn(Boolean success) in /Users/shana/code/work/github/Unity/src/GitHub.Api/Tasks/ActionTask.cs:line 422
   at GitHub.Unity.TaskBase`1[[GitHub.Unity.LoginResultData, GitHub.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].RunSynchronously() in /Users/shana/code/work/github/Unity/src/GitHub.Api/Tasks/TaskBase.cs:line 685
   at System.Threading.Tasks.Task`1[[GitHub.Unity.LoginResultData, GitHub.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].InvokeFuture(System.Object futureAsObj)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object obj)
   at System.Security.SecurityContext.Run(System.Security.SecurityContext securityContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Security/SecurityContext.cs:line 150
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.TaskScheduler.TryExecuteTask(System.Threading.Tasks.Task task)
   at GitHub.Unity.ThreadPerTaskScheduler+<QueueTask>c__AnonStorey0.<>m__0() in /Users/shana/code/work/github/Unity/src/GitHub.Api/Tasks/ConcurrentExclusiveInterleave.cs:line 440`

**Comment by StanleyGoldman** [comment]
Chances are this will be solved by proper SSH support.

**Comment by shana** [comment]
@TheKrane Thanks for the report, we haven't tested much on Linux so it's not surprising there's bugs there. Where is git installed on your system, and is it on your path?

**Comment by TheKrane** [comment]
Git is installed to the default location, which should be /usr/bin/git.
The plugin is acting really strange. It's not just that you can't login.
In the settings tab the git directory is always empty, even if I manually specify it and hit save.

**Comment by shana** [comment]
Could you upload the github-unity.log file? The path to it should show up when you first start up unity with the extension installed.

**Comment by StanleyGoldman** [comment]
:wave: @TheKrane 

Can you do me a favor and try again with the latest version of GitHub for Unity?
Things have changed since then and I'd like to get an idea of how well it works at this point.

**Comment by StanleyGoldman** [comment]
Hey @TheKrane I haven't heard from you and we already have an issue open for linux support. #555 
So I'm gonna close this one out.
