### ISSUE TITLE
Repository with no commits causes error

### ISSUE THREAD

**Issue by StanleyGoldman** [github-for-unity/Unity#926]
```
181006-07:57:26.126  INFO [ 2] <OctorunInstaller>                  MoveOctorun fromPath: T:\octorun_extract_archive_path_1090015165\octorun toPath:C:\Users\illuminati-user\AppData\Local\GitHubUnity\octorun
181006-07:57:26.127  INFO [ 2] <OctorunInstaller>                  DeleteContents toPath:C:\Users\illuminati-user\AppData\Local\GitHubUnity\octorun
181006-07:57:26.129  INFO [ 2] <OctorunInstaller>                  MoveFiles fromPath: T:\octorun_extract_archive_path_1090015165\octorun toPath:C:\Users\illuminati-user\AppData\Local\GitHubUnity\octorun
181006-07:57:27.691  INFO [ 2] <OctorunInstaller>                  Delete fromPath.Parent:T:\octorun_extract_archive_path_1090015165
181006-07:59:27.576  INFO [ 2] <GitInstaller>                      Moving Git source:T:\git_zip_extract_zip_paths_624345651\git target:C:\Users\illuminati-user\AppData\Local\GitHubUnity\git
181006-07:59:27.578  INFO [ 2] <GitInstaller>                      DeleteContents target:C:\Users\illuminati-user\AppData\Local\GitHubUnity\git
181006-07:59:27.580  INFO [ 2] <GitInstaller>                      MoveFiles fromPath: T:\git_zip_extract_zip_paths_624345651\git toPath:C:\Users\illuminati-user\AppData\Local\GitHubUnity\git
181006-08:00:14.897  INFO [ 2] <GitInstaller>                      Delete source:T:\git_zip_extract_zip_paths_624345651\git
181006-08:00:16.835  INFO [ 2] <GitInstaller>                      Moving GitLFS source:T:\git_zip_extract_zip_paths_624345651\git-lfs target:C:\Users\illuminati-user\AppData\Local\GitHubUnity\git-lfs
181006-08:00:16.836  INFO [ 2] <GitInstaller>                      DeleteContents target:C:\Users\illuminati-user\AppData\Local\GitHubUnity\git-lfs
181006-08:00:16.857  INFO [ 2] <GitInstaller>                      MoveFiles fromPath: T:\git_zip_extract_zip_paths_624345651\git-lfs toPath:C:\Users\illuminati-user\AppData\Local\GitHubUnity\git-lfs
181006-08:00:16.883  INFO [ 2] <GitInstaller>                      Delete source:T:\git_zip_extract_zip_paths_624345651\git-lfs
181006-08:00:19.711 ERROR [17] <TaskManager>                       Exception on concurrent thread: 1 git log
GitHub.Unity.ProcessException: fatal: your current branch 'master' does not have any commits yet
  at GitHub.Unity.ProcessTaskWithListOutput`1+<RunWithReturn>c__AnonStorey0[GitHub.Unity.GitLogEntry].<>m__1 () [0x00101] in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Tasks\ProcessTask.cs:498 
  at GitHub.Unity.ProcessWrapper.Run () [0x00424] in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Tasks\ProcessTask.cs:199 
  at GitHub.Unity.ProcessTaskWithListOutput`1[GitHub.Unity.GitLogEntry].RunWithReturn (Boolean success) [0x00061] in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Tasks\ProcessTask.cs:506 
  at GitHub.Unity.TaskBase`1[TResult].RunSynchronously () [0x0007c] in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Tasks\TaskBase.cs:685 
  at System.Threading.Tasks.Task`1[System.Collections.Generic.List`1[GitHub.Unity.GitLogEntry]].InvokeFuture (System.Object futureAsObj) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <filename unknown>:0 
=======
   at GitHub.Unity.TaskManager+<ScheduleConcurrent>c__AnonStorey2`1[[GitHub.Unity.TaskBase, GitHub.Api, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null]].<>m__0(System.Threading.Tasks.Task tt) in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Tasks\TaskManager.cs:line 146
   at System.Threading.Tasks.Task+<>c__DisplayClass6.<ContinueWith>b__5(System.Object obj)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object obj)
   at System.Security.SecurityContext.Run(System.Security.SecurityContext securityContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Security/SecurityContext.cs:line 150
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.TaskScheduler.TryExecuteTask(System.Threading.Tasks.Task task)
   at GitHub.Unity.ThreadPerTaskScheduler+<QueueTask>c__AnonStorey0.<>m__0() in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Tasks\ConcurrentExclusiveInterleave.cs:line 440
181006-08:00:19.712 ERROR [18] <TaskManager>                       Exception on concurrent thread: 2 ActionTask
GitHub.Unity.ProcessException: fatal: Needed a single revision
  at GitHub.Unity.ProcessTask`1+<RunWithReturn>c__AnonStorey0[System.String].<>m__1 () [0x0013e] in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Tasks\ProcessTask.cs:371 
  at GitHub.Unity.ProcessWrapper.Run () [0x00424] in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Tasks\ProcessTask.cs:199 
  at GitHub.Unity.ProcessTask`1[T].RunWithReturn (Boolean success) [0x00061] in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Tasks\ProcessTask.cs:380 
  at GitHub.Unity.TaskBase`1[TResult].RunSynchronously () [0x0007c] in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Tasks\TaskBase.cs:685 
  at GitHub.Unity.RepositoryManager.<UpdateRepositoryInfo>m__9 () [0x0000a] in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Git\RepositoryManager.cs:431 
  at GitHub.Unity.ActionTask+<ActionTask>c__AnonStorey0.<>m__0 (Boolean _) [0x00000] in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Tasks\ActionTask.cs:292 
  at GitHub.Unity.ActionTask.Run (Boolean success) [0x00007] in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Tasks\ActionTask.cs:317 
=======
   at GitHub.Unity.TaskManager+<ScheduleConcurrent>c__AnonStorey2`1[[GitHub.Unity.TaskBase, GitHub.Api, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null]].<>m__0(System.Threading.Tasks.Task tt) in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Tasks\TaskManager.cs:line 146
   at System.Threading.Tasks.Task+<>c__DisplayClass6.<ContinueWith>b__5(System.Object obj)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object obj)
   at System.Security.SecurityContext.Run(System.Security.SecurityContext securityContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Security/SecurityContext.cs:line 150
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.TaskScheduler.TryExecuteTask(System.Threading.Tasks.Task task)
   at GitHub.Unity.ThreadPerTaskScheduler+<QueueTask>c__AnonStorey0.<>m__0() in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Tasks\ConcurrentExclusiveInterleave.cs:line 440
```

**Comment by sguthals** [comment]
Testing: 
- create a project
- goto the command line, type `git init`
- to create a repo with no commits
- install the plugin

**Comment by sguthals** [comment]
Logs:
```
181010-13:10:33.447  INFO [ 1] <Global>                            Initializing GitHubForUnity:'v1.1.0' Unity:'v2017.3.1f1'
181010-13:10:33.495 TRACE [ 3] <DownloadTask>                      Download of http://github-vs.s3.amazonaws.com/unity/latest.json to /Users/sguthals/Library/Application Support/GitHubUnity/latest.json Attempt 1 of 1
181010-13:10:33.548 TRACE [ 2] <ProcessWrapper>                    Running 'bash -c "/usr/libexec/path_helper"'
181010-13:10:33.653 TRACE [ 3] <DownloadTask>                      Downloading http://github-vs.s3.amazonaws.com/unity/latest.json
181010-13:10:33.721 TRACE [ 2] <IApplicationManager>               Existing Environment Path Original:/usr/bin:/bin:/usr/sbin:/sbin Updated:PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/munki:/Library/Frameworks/Mono.framework/Versions/Current/Commands"; export PATH;

181010-13:10:33.727  WARN [ 2] <OctorunInstaller>                  Current version f497f7aa3d does not match expected 902910f4
181010-13:10:33.738 TRACE [ 2] <UnzipTask>                         Unzip File: /Users/sguthals/Library/Application Support/GitHubUnity/downloads/octorun.zip to Path: /var/folders/ls/bcwyd6454qb2y1z6ypnm_mlc0000gn/T/octorun_extract_archive_path_1776254635
181010-13:10:33.826 TRACE [ 2] <OctorunInstaller>                  MoveOctorun fromPath: /var/folders/ls/bcwyd6454qb2y1z6ypnm_mlc0000gn/T/octorun_extract_archive_path_1776254635/octorun toPath:/Users/sguthals/Library/Application Support/GitHubUnity/octorun
181010-13:10:33.827 TRACE [ 2] <CopyHelper>                        CopyFolder fromPath: /var/folders/ls/bcwyd6454qb2y1z6ypnm_mlc0000gn/T/octorun_extract_archive_path_1776254635/octorun toPath:/Users/sguthals/Library/Application Support/GitHubUnity/octorun
181010-13:10:33.843 TRACE [ 2] <ProcessWrapper>                    Running '/usr/local/bin/git --version'
181010-13:10:33.974 TRACE [ 2] <ProcessWrapper>                    Running '/Users/sguthals/Library/Application Support/GitHubUnity/git-lfs/git-lfs version'
181010-13:10:34.169 TRACE [ 2] <ProcessWrapper>                    Running '/usr/local/bin/git config --replace-all --local merge.unityyamlmerge.cmd "'/Applications/Unity 2017.3/Unity.app/Contents/Tools/UnityYAMLMerge' merge -p '$BASE' '$REMOTE' '$LOCAL' '$MERGED'"'
181010-13:10:34.297 TRACE [ 2] <ProcessWrapper>                    Running '/usr/local/bin/git config --replace-all --local merge.unityyamlmerge.trustExitCode "false"'
181010-13:10:34.424 TRACE [ 2] <ProcessWrapper>                    Running '/usr/local/bin/git lfs install'
181010-13:10:34.663 TRACE [ 2] <RepositoryWatcher>                 Watching Path: "/Users/sguthals/10Oct2018_2"
181010-13:10:34.666 TRACE [ 2] <IApplicationManager>               Got a repository? /Users/sguthals/10Oct2018_2
181010-13:10:34.681 TRACE [ 3] <DownloadTask>                      Downloading http://github-vs.s3.amazonaws.com/unity/latest.json StatusCode:200
181010-13:10:34.687 TRACE [ 3] <Global>                            Skipping GitHub for Unity update v1.0.3, we already have it
181010-13:10:58.466 TRACE [ 1] <IApplicationManager>               Restarted /Users/sguthals/10Oct2018_2
181010-13:10:58.479 TRACE [ 1] <GitLocksCache>                     needsInvalidation isInitialized:False timedOut:True
181010-13:10:58.485 TRACE [ 1] <RepositoryInfoCache>               needsInvalidation isInitialized:False timedOut:True
181010-13:10:58.508 TRACE [ 4] <ProcessWrapper>                    Running '/Users/sguthals/Library/Application Support/GitHubUnity/git-lfs/git-lfs locks --json'
181010-13:10:58.545 TRACE [ 1] <GitStatusCache>                    needsInvalidation isInitialized:False timedOut:True
181010-13:10:58.564 TRACE [ 6] <ProcessWrapper>                    Running '/usr/local/bin/git -c i18n.logoutputencoding=utf8 -c core.quotepath=false status -b -u --porcelain'
181010-13:10:59.861 TRACE [ 6] <ProcessWrapper>                    Running '/usr/local/bin/git -c i18n.logoutputencoding=utf8 -c core.quotepath=false status -b -u --porcelain'
181010-13:11:01.379 TRACE [ 1] <GitUserCache>                      needsInvalidation isInitialized:False timedOut:True
181010-13:11:01.383 TRACE [14] <ProcessWrapper>                    Running '/usr/local/bin/git config --get --global user.name'
181010-13:11:01.426 TRACE [ 1] <GitLogCache>                       needsInvalidation isInitialized:False timedOut:True
181010-13:11:01.432 TRACE [15] <ProcessWrapper>                    Running '/usr/local/bin/git -c i18n.logoutputencoding=utf8 -c core.quotepath=false log --pretty=format:"%H%n%P%n%aN%n%aE%n%aI%n%cN%n%cE%n%cI%n%B---GHUBODYEND---" --name-status'
181010-13:11:01.452 TRACE [16] <ProcessWrapper>                    fatal: your current branch 'master' does not have any commits yet
181010-13:11:01.511 TRACE [20] <ProcessWrapper>                    Running '/usr/local/bin/git config --get --global user.email'
181010-13:11:13.984 TRACE [29] <ProcessWrapper>                    Running '/usr/local/bin/git -c i18n.logoutputencoding=utf8 -c core.quotepath=false status -b -u --porcelain'
181010-13:11:14.921 TRACE [32] <ProcessWrapper>                    Running '/usr/local/bin/git -c i18n.logoutputencoding=utf8 -c core.quotepath=false status -b -u --porcelain'
181010-13:11:20.312 TRACE [35] <ProcessWrapper>                    Running '/usr/local/bin/git config --get-all credential.helper'
181010-13:11:20.446 TRACE [35] <ProcessWrapper>                    Running '/usr/local/bin/git credential-osxkeychain get'
181010-13:11:20.612 TRACE [35] <ProcessWrapper>                    Running '/Applications/Unity 2017.3/Unity.app/Contents/Tools/nodejs/bin/node "/Users/sguthals/Library/Application Support/GitHubUnity/octorun/src/bin/app.js" validate'
181010-13:11:23.253 TRACE [36] <ProcessWrapper>                    Running '/Applications/Unity 2017.3/Unity.app/Contents/Tools/nodejs/bin/node "/Users/sguthals/Library/Application Support/GitHubUnity/octorun/src/bin/app.js" organizations'
181010-13:11:33.473 TRACE [37] <ProcessWrapper>                    Running '/Applications/Unity 2017.3/Unity.app/Contents/Tools/nodejs/bin/node "/Users/sguthals/Library/Application Support/GitHubUnity/octorun/src/bin/app.js" publish -r "10Oct2018_2"'
181010-13:11:37.210 TRACE [39] <ProcessWrapper>                    Running '/usr/local/bin/git remote add origin https://github.com/sguthals/10Oct2018_2.git'
181010-13:11:37.344 TRACE [39] <RepositoryWatcher>                 Watching Path: "/Users/sguthals/10Oct2018_2"
181010-13:11:37.346 TRACE [39] <ProcessWrapper>                    Running '/usr/local/bin/git push -u origin master:master'
181010-13:11:37.402 TRACE [41] <ProcessWrapper>                    error: src refspec master does not match any.
181010-13:11:37.402 TRACE [41] <ProcessWrapper>                    error: failed to push some refs to 'https://github.com/sguthals/10Oct2018_2.git'
181010-13:11:37.522 ERROR [42] <TaskManager>                       Exception on exclusive thread: 1 push -u origin master:master
GitHub.Unity.ProcessException: error: src refspec master does not match any.
error: failed to push some refs to 'https://github.com/sguthals/10Oct2018_2.git'
  at GitHub.Unity.ProcessTask`1+<RunWithReturn>c__AnonStorey0[System.String].<>m__1 () [0x0013e] in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Tasks\ProcessTask.cs:371 
  at GitHub.Unity.ProcessWrapper.Run () [0x00424] in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Tasks\ProcessTask.cs:199 
  at GitHub.Unity.ProcessTask`1[T].RunWithReturn (Boolean success) [0x00061] in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Tasks\ProcessTask.cs:380 
  at GitHub.Unity.TaskBase`1[TResult].RunSynchronously () [0x0007c] in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Tasks\TaskBase.cs:685 
  at System.Threading.Tasks.Task`1[System.String].InvokeFuture (System.Object futureAsObj) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <filename unknown>:0 
=======
   at GitHub.Unity.TaskManager+<ScheduleExclusive>c__AnonStorey1`1[[GitHub.Unity.TaskBase, GitHub.Api, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null]].<>m__0(System.Threading.Tasks.Task tt) in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Tasks\TaskManager.cs:line 128
   at System.Threading.Tasks.Task+<>c__DisplayClass6.<ContinueWith>b__5(System.Object obj)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object obj)
   at System.Security.SecurityContext.Run(System.Security.SecurityContext securityContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Security/SecurityContext.cs:line 150
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.TaskScheduler.TryExecuteTask(System.Threading.Tasks.Task task)
   at GitHub.Unity.ThreadPerTaskScheduler+<QueueTask>c__AnonStorey0.<>m__0() in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Tasks\ConcurrentExclusiveInterleave.cs:line 440
181010-13:11:37.533 TRACE [45] <ProcessWrapper>                    Running '/usr/local/bin/git -c i18n.logoutputencoding=utf8 -c core.quotepath=false log --pretty=format:"%H%n%P%n%aN%n%aE%n%aI%n%cN%n%cE%n%cI%n%B---GHUBODYEND---" --name-status'
181010-13:11:37.557 TRACE [46] <ProcessWrapper>                    fatal: your current branch 'master' does not have any commits yet
```

**Comment by sguthals** [comment]
Stuck with this:
<img width="357" alt="screen shot 2018-10-10 at 1 12 46 pm" src="https://user-images.githubusercontent.com/1314285/46763283-3a47b380-cc8e-11e8-9476-f746119f3612.png">

**Comment by sguthals** [comment]
Seems like this one is now triggering the error: https://github.com/github-for-unity/Unity/issues/871
