### ISSUE TITLE
Login failed when two-factor authentication is enabled

### ISSUE THREAD

**Issue by shiena** [github-for-unity/Unity#96]
OS: Windows10
Unity: 5.6.0f3
GitHub for Unity: 0.13.0.0

**github-unity.log**

```
170705-00:36:54  INFO [ 1] <Global>                            Initializing GitHub for Unity version 0.13.0.0
170705-00:38:21  INFO [ 1] <LoginManager>                      Login Username:shiena
170705-00:38:23  WARN [ 1] <LoginManager>                      Login Exception
An error occurred while sending the request
  at System.Net.Http.HttpClientHandler+<SendAsync>c__async0.MoveNext () [0x00000] in <filename unknown>:0 
   at GitHub.Unity.LogFacade.Warning(System.Exception ex, System.String message) in D:\code\github\Unity\src\GitHub.Logging\LogFacade.cs:line 120
   at GitHub.Unity.LoginManager+<Login>c__async0.MoveNext() in D:\code\github\Unity\src\GitHub.Api\Authentication\LoginManager.cs:line 124
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object stateMachine)
   at System.Security.SecurityContext.Run(System.Security.SecurityContext securityContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Security/SecurityContext.cs:line 150
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Runtime.CompilerServices.TaskAwaiter+<>c__DisplayClassa.<OnCompletedInternal>b__1(System.Object state)
   at GitHub.Unity.MainThreadSynchronizationContext+<Post>c__AnonStorey1.<>m__0() in D:\code\github\Unity\src\UnityExtension\Assets\Editor\GitHub.Unity\Logging\UnityLogAdapter.cs:line 22
   at UnityEditor.EditorApplication.Internal_CallDelayFunctions() in C:\buildslave\unity\build\Editor\Mono\EditorApplication.cs:line 118

```

The last security history at that time is **user.two_factor_requested**

**Comment by StanleyGoldman** [comment]
Hey @shiena 🙇Thanks for testing. 2FA works for me, but something is obviously wrong. Does it happen every time?

We need better logs, in a future release we will add code to capture more information about the login error.

**Comment by StanleyGoldman** [comment]
Do you use a proxy?

**Comment by shiena** [comment]
@StanleyGoldman 
Yes, I tried login many times, but I have never succeeded.
And no proxy.

**Comment by StanleyGoldman** [comment]
So the patch I need to make, I will be logging the headers that come in that error response.
It's something we need for the future, but it does not help me help you right now.

Would you be able to capture the headers in that http response for me? Using a tool like [Fiddler](http://www.telerik.com/fiddler) perhaps?

**Comment by StanleyGoldman** [comment]
If you don't feel comfortable, no worries, we will figure it out.

**Comment by StanleyGoldman** [comment]
Well I have some good news...

```
170705-17:04:22 TRACE [ 1] <Keychain>                          SetCredentials Host:https://github.com/
170705-17:04:22  INFO [ 1] <LoginManager>                      Login Username:StanleyGoldman
170705-17:04:24  WARN [ 1] <LoginManager>                      Login Exception
An error occurred while sending the request
  at System.Net.Http.HttpClientHandler+<SendAsync>c__async0.MoveNext () [0x00000] in <filename unknown>:0 
   at GitHub.Unity.LogFacade.Warning(System.Exception ex, System.String message) in /Users/stanleygoldman/Documents/Unity/src/GitHub.Logging/LogFacade.cs:line 120
   at GitHub.Unity.LoginManager+<Login>c__async0.MoveNext() in /Users/stanleygoldman/Documents/Unity/src/GitHub.Api/Authentication/LoginManager.cs:line 124
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object stateMachine)
   at System.Security.SecurityContext.Run(System.Security.SecurityContext securityContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Security/SecurityContext.cs:line 150
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Runtime.CompilerServices.TaskAwaiter+<>c__DisplayClassa.<OnCompletedInternal>b__1(System.Object state)
   at GitHub.Unity.MainThreadSynchronizationContext+<Post>c__AnonStorey1.<>m__0() in /Users/stanleygoldman/Documents/Unity/src/UnityExtension/Assets/Editor/GitHub.Unity/Threading/SingleThreadSynchronizationContext.cs:line 23
   at UnityEditor.EditorApplication.Internal_CallDelayFunctions() in C:\buildslave\unity\build\artifacts\generated\common\editor\EditorApplicationBindings.gen.cs:line 207
```

**Comment by shana** [comment]
We've just released a new build https://github.com/github-for-unity/Unity/releases/tag/v0.15-alpha that will hopefully fix this issue, could you test and let us know please?

**Comment by shiena** [comment]
@shana Thank you!  v0.15-alpha was able to login with two-factor authentication.

**Comment by ThomasAunvik** [comment]
*Wants to re-open this issue*. I have 2FA too, but i cannot login to my account. My username and password is definetly correct. Using Unity 2017.2.0f3
Log: https://gist.github.com/ThomasAunvik/3216de5a512776484fac13a8ad3ee928

**Comment by StanleyGoldman** [comment]
Oh boy...
@ThomasAunvik create a new issue with your details and this log.
This is a completely different issue i'm afraid.
