### ISSUE TITLE
Disable option to pull until branch has remote ref

### ISSUE THREAD

**Issue by meaghanlewis** [github-for-unity/Unity#984]
### Steps to Reproduce

1. Create new branch
2. Checkout branch
3. Press `Pull`

**Expected behavior:** 
A friendlier message on failure or not being given the option to pull at all

**Actual behavior:** 
![screen shot 2018-12-13 at 1 51 25 pm](https://user-images.githubusercontent.com/10103121/49969799-50682f00-fede-11e8-90b0-181e30301172.png)

Error from log:
```
181213-13:51:21.839 TRACE [558] <ProcessWrapper>                    Running '/usr/local/bin/git pull origin branch3'
181213-13:51:22.543 TRACE [15] <ProcessWrapper>                    fatal: Couldn't find remote ref branch3
181213-13:51:22.649 TRACE [558] <RepositoryWatcher>                 Watching Path: "/Users/meaghanlewis/Unity Projects/SpaceInvaders"
181213-13:51:22.650 TRACE [558] <RepositoryWatcher>                 Watching Path: "/Users/meaghanlewis/Unity Projects/SpaceInvaders"
181213-13:51:22.652 ERROR [559] <TaskManager>                       Exception on exclusive thread: 2 pull origin branch3
GitHub.Unity.ProcessException: fatal: Couldn't find remote ref branch3
  at GitHub.Unity.ProcessTask`1+<RunWithReturn>c__AnonStorey0[System.String].<>m__1 () [0x0013e] in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Tasks\ProcessTask.cs:371 
  at GitHub.Unity.ProcessWrapper.Run () [0x00424] in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Tasks\ProcessTask.cs:199 
  at GitHub.Unity.ProcessTask`1[T].RunWithReturn (Boolean success) [0x00061] in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Tasks\ProcessTask.cs:380 
  at GitHub.Unity.TaskBase`1[TResult].RunSynchronously () [0x0007c] in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Tasks\TaskBase.cs:685 
  at System.Threading.Tasks.Task`1[System.String].InvokeFuture (System.Object futureAsObj) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <filename unknown>:0 
=======
   at GitHub.Unity.TaskManager+<ScheduleExclusive>c__AnonStorey1`1[[GitHub.Unity.TaskBase, GitHub.Api, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null]].<>m__0(System.Threading.Tasks.Task tt) in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Tasks\TaskManager.cs:line 128
   at System.Threading.Tasks.Task+<>c__DisplayClass6.<ContinueWith>b__5(System.Object obj)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object obj)
   at System.Security.SecurityContext.Run(System.Security.SecurityContext securityContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Security/SecurityContext.cs:line 150
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.TaskScheduler.TryExecuteTask(System.Threading.Tasks.Task task)
   at GitHub.Unity.ThreadPerTaskScheduler+<QueueTask>c__AnonStorey0.<>m__0() in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Tasks\ConcurrentExclusiveInterleave.cs:line 440
```
**Reproduces how often:** 100

**Comment by meaghanlewis** [comment]
I'm not sure whether to call this a `bug` or `enhancement`.
